DKU-Dgaja/gitudy

.github/workflows/CICD_dev_be_merge.yml
.github/workflows/CI_dev_be_pull_request.yml
backend/Dockerfile-dev
backend/build.gradle

CD 파이프라인 추가

---

backend/src/main/java/com/example/backend/auth/config/ProjectConfig.java
backend/src/main/java/com/example/backend/auth/config/security/SecurityConfig.java
backend/src/main/java/com/example/backend/auth/config/swagger/SwaggerConfig.java

ex) #이슈번호
어떤 변경 사항이 있나요?
* ProjectConfig : prod, !prod로 구분, dev 환경에서는 모든 url 허용
* SecurityConfig : swagger url추가
* Swagger Info, Servers, SecurityScheme 설정
피드백 감사하겠습니다ㅎㅎ

Feat(#53) swagger setting

---

backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
backend/src/main/java/com/example/backend/auth/api/service/jwt/JwtService.java
backend/src/main/java/com/example/backend/auth/api/service/oauth/adapter/github/GithubAdapter.java
backend/src/main/java/com/example/backend/auth/api/service/oauth/response/OAuthResponse.java
backend/src/main/java/com/example/backend/auth/config/security/filter/JwtAuthenticationFilter.java
backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
backend/src/main/java/com/example/backend/domain/define/user/User.java
backend/src/main/java/com/example/backend/domain/define/user/repository/UserRepository.java
backend/src/test/java/com/example/backend/auth/TestConfig.java
backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
backend/src/test/java/com/example/backend/auth/api/service/jwt/JwtServiceTest.java
backend/src/test/java/com/example/backend/auth/api/service/oauth/OAuthServiceTest.java
backend/src/test/java/com/example/backend/auth/api/service/oauth/adapter/github/GithubAdapterTest.java
backend/src/test/java/com/example/backend/auth/api/service/oauth/builder/github/GithubURLBuilderTest.java
backend/src/test/java/com/example/backend/auth/config/security/SecurityConfigTest.java
backend/src/test/java/com/example/backend/common/exception/GlobalExceptionHandlerTest.java
backend/src/test/java/com/example/backend/domain/define/user/repository/UserRepositoryTest.java
backend/src/test/java/com/example/backend/external/clients/oauth/github/GithubClientTest.java

#38 
어떤 변경 사항이 있나요?
- User Entity email, phoneNumber 필드 삭제
- User Entity 다중 필드(platformId, platformType)에 유니크 제약조건 걸기
- 시큐리티 식별자인 User의 getUsername()을 email에서 platformId + "_" + platformType로 변경
- 유니크 제약조건 테스트
email 필드를 제거하면서 시큐리티의 식별자인 getUsername()의 반환값을 platformId + "_" + platformType으로 변경했는데요. getUsername()이 저희 주요 필터인 JWT 필터 외의 다른 필터에서도 사용되는 것 같습니다. 그래서 Security Context에 넣어줄 Authentication 객체를 만들 때 기존에 하던 방법처럼 claims 정보만으로 UserDetails를 생성하면 이후의 필터에서 getUsername() 사용시 NullPointerException이 발생해요. 일단은 그냥 Subject에서 값들을 추출해 넣어줬는데 이렇게 하는 게 맞는지 잘 모르겠어요 😥

[BE] refactor(#38): User Entity 다중 필드(platformId, platformType)에 유니크 제약조건 걸기

---

backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
backend/src/main/java/com/example/backend/auth/api/controller/auth/request/AuthRegisterRequest.java
backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
backend/src/main/java/com/example/backend/auth/api/service/auth/request/AuthServiceRegisterRequest.java
backend/src/main/java/com/example/backend/auth/api/service/auth/response/AuthServiceLoginResponse.java
backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
backend/src/main/java/com/example/backend/common/exception/auth/AuthException.java
backend/src/main/java/com/example/backend/domain/define/account/user/User.java
backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java

#65
어떤 변경 사항이 있나요?
회원가입
- platformId, platformType 받아서 데이터베이스에 저장
- platformId, platformType와 함께 githubEmail 입력받아서 이메일 검증
- 회원가입 성공하면 JWT Access Token, Refresh Token 재발급 후 response
회원탈퇴
- User status를 WITHDRAW로 변경
아마 제가 생각 못한 부분이 많을거 같은데 리뷰 부탁드립니다~
AuthControllerTest에 존재하는 [올바른 사용자의 토큰으로 사용자 계정 탈퇴 요청을 하면, 계정이 삭제된다.] 테스트는 오류가 납니다.
테스트 함수 이름만 바꿔서 AuthServiceTest에 [22222222222]라는 이름으로 똑같은 코드로 돌려보니 성공합니다.
같은 코드인데 왜 테스트 성공 유무가 다른지 모르겠습니다. (해결)

[BE] Feat(#65):  회원가입 및 탈퇴 구현

---

backend/src/main/java/com/example/backend/common/exception/study/StudyInfoException.java
backend/src/main/java/com/example/backend/domain/define/study/category/info/repository/StudyCategoryRepository.java
backend/src/main/java/com/example/backend/domain/define/study/category/mapping/repository/StudyCategoryMappingRepository.java
backend/src/main/java/com/example/backend/domain/define/study/info/StudyInfo.java
backend/src/main/java/com/example/backend/domain/define/study/member/StudyMember.java
backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepository.java
backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java
backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
backend/src/test/java/com/example/backend/auth/config/fixture/UserFixture.java
backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java
backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java

#124
어떤 변경 사항이 있나요?
* 스터디 삭제 api구현
1. studyInfoId로 스터디가 있는 지 확인
2. 스터디장이 맞는지 확인
3. 스터디 상태정보를 STUDY_DELETED로 변경
4. 모든 스터디원의 상태정보를 Withdrawal로 변경 
* 스터디 삭제 api 테스트, 예외 테스트 
스터디 삭제 부분에서 모든 데이터를 삭제하려했으나 끝난 스터디에 대한 정보도 볼 수 있게 하는 것이 좋은 거 같아 데이터를 남겨두었습니다!
피드백 부탁드립니다~!

[BE] feat(#124): 스터디 삭제 api 구현

---

backend/src/main/java/com/example/backend/domain/define/study/comment/study/repository/StudyCommentRepository.java
backend/src/main/java/com/example/backend/domain/define/study/comment/study/repository/StudyCommentRepositoryCustom.java
backend/src/main/java/com/example/backend/domain/define/study/comment/study/repository/StudyCommentRepositoryImpl.java
backend/src/main/java/com/example/backend/study/api/controller/comment/study/StudyCommentController.java
backend/src/main/java/com/example/backend/study/api/controller/comment/study/response/StudyCommentListAndCursorIdxResponse.java
backend/src/main/java/com/example/backend/study/api/controller/comment/study/response/StudyCommentResponse.java
backend/src/main/java/com/example/backend/study/api/service/comment/study/StudyCommentService.java
backend/src/main/java/com/example/backend/study/api/service/comment/study/response/UserInfoForStudyCommentResponse.java
backend/src/test/java/com/example/backend/domain/define/study/comment/StudyCommentFixture.java
backend/src/test/java/com/example/backend/domain/define/study/comment/study/repository/StudyCommentRepositoryTest.java
backend/src/test/java/com/example/backend/study/api/controller/comment/study/StudyCommentControllerTest.java
backend/src/test/java/com/example/backend/study/api/service/comment/study/StudyCommentServiceTest.java

ex) #158
어떤 변경 사항이 있나요?
스터디 댓글 리스트 조회 api 구현
현재 원래 만들어져 있던 UserInfoResponse를 사용했는데 정보가 너무 많은가요??
댓글에는 유저 프로필이랑 이름정도만 들어가기 때문에 새로운 DTO를 생성해서 프로필 URL이랑 이름 정도만 넣어주는 방식으로 하는게 좋을까요??
피드백 부탁드립니다~~!

[BE] feat(#158): 스터디 댓글 리스트 조회 api 구현

---

backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
backend/src/main/java/com/example/backend/auth/api/controller/auth/request/UserNameRequest.java
backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
backend/src/main/java/com/example/backend/domain/define/account/user/repository/UserRepository.java
backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
backend/src/test/java/com/example/backend/auth/config/fixture/UserFixture.java

#213 
어떤 변경 사항이 있나요?
닉네임 중복체크 api
QueryDsl에서 exist 메서드 쓰는것보다 JPA의 exists 메서드를 사용
JPA exists메서드는 선택된 항이 하나라도 존재하면 즉시 처리를 멈추고 결과를 반환하는데
QueryDsl exist 메서드는 실제로 count() > 0 으로 실행한다고 해서 성능이슈..? ㅎㅎ
맞게 한건지 모르겠어요 ㅠㅠ 피드백 부탁드립니다..

[BE] feat(#213): 닉네임 중복체크 api

---

backend/src/main/java/com/example/backend/domain/define/fcmToken/FcmToken.java
backend/src/main/java/com/example/backend/domain/define/fcmToken/repository/FcmTokenRepository.java
backend/src/main/java/com/example/backend/study/api/event/controller/FcmController.java
backend/src/main/java/com/example/backend/study/api/event/controller/request/FcmTokenSaveRequest.java
backend/src/main/java/com/example/backend/study/api/event/service/FcmService.java
backend/src/test/java/com/example/backend/domain/define/fcmToken/repository/FcmTokenRepositoryTest.java
backend/src/test/java/com/example/backend/study/api/event/controller/FcmControllerTest.java
backend/src/test/java/com/example/backend/study/api/event/service/FcmServiceTest.java

ex) #243
어떤 변경 사항이 있나요?
key : userId
value : FCM token
* #244와 충돌을 우려해 빈칸이 많습니다.
* 패키지 구조 토의 후 구조 확정되면 controller, service test 추가해서 올리겠습니다.
리뷰 부탁드립니다!

[BE] feat(#243): redis FCM token 저장 api 구현

---

backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
backend/src/main/java/com/example/backend/domain/define/fcm/listener/TodoRegisterMemberListener.java
backend/src/main/java/com/example/backend/domain/define/study/todo/event/TodoRegisterMemberEvent.java
backend/src/main/java/com/example/backend/study/api/event/service/FcmService.java
backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
backend/src/main/java/com/example/backend/study/api/service/user/UserService.java
backend/src/test/java/com/example/backend/auth/config/fixture/UserFixture.java
backend/src/test/java/com/example/backend/domain/define/event/FcmFixture.java
backend/src/test/java/com/example/backend/domain/define/fcm/listener/TodoRegisterMemberListenerTest.java
backend/src/test/java/com/example/backend/domain/define/study/todo/TodoEventFixture.java
backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java

#275 
어떤 변경 사항이 있나요?
Todo 등록 멤버 알림전송(fcm) api
List User 객체로 반환해서 알림 갈때 name필드도 사용할 생각도 해보았지만 가져오는데 복잡하기도 하고 쿼리가 많아지고
name필드 하나 쓰려고 가져오는게 너무 비효율적인거 같아서 isPushAlarmYn 필드가 true 인 멤버들의 userId만 추출해서 가져왔습니다. + sendMultiDevice() 메서드를 사용하기 위해서 tokens만 따로 추출하는데 FcmToken에 name필드는 따로 존재 하지 않아서 name이 잘못 가는 경우 발생할 수 있을듯 (=> userId로 해당 토큰이 맞는지 비교까지해야함)
놓친거 있으면 피드백주세요!

[BE] feat(#275): Todo 등록 멤버 알림전송(fcm) api

---

android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/study/GitudyStudyApi.kt
android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/ConventionResponse.kt
android/gitudy/data/src/main/java/com/takseha/data/repository/study/GitudyStudyRepository.kt
android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/home/MainHomeFragment.kt
android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/CommitConventionActivity.kt
android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyHomeFragment.kt
android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyMainActivity.kt
android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/home/MainHomeViewModel.kt
android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/CommitConventionViewModel.kt
android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/MyStudyMainViewModel.kt
android/gitudy/presentation/src/main/res/layout/activity_commit_convention.xml
android/gitudy/presentation/src/main/res/layout/activity_my_study_main.xml
android/gitudy/presentation/src/main/res/values/strings.xml

#334
어떤 변경 사항이 있나요?
마이스터디 메인 페이지 내에서 기등록된 커밋 컨벤션 정보를 나타내는 기능 구현
호출한 커밋 컨벤션 정보를 커밋 컨벤션 상세페이지로 전달하여 화면에 표시하는 기능 구현
- /study/{studyInfoId}/convention api 호출
https://github.com/DKU-Dgaja/gitudy/assets/86196342/abbb2395-d9d3-452f-aa37-36aa0d9bf846

[AN] feat(#334): 마이스터디 메인 페이지 내 커밋 컨벤션 정보 api 호출 기능 구현

---

backend/src/main/java/com/example/backend/BackendApplication.java
backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java
backend/src/main/java/com/example/backend/auth/config/security/filter/JwtAuthenticationFilter.java
backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
backend/src/main/java/com/example/backend/common/exception/GlobalExceptionHandler.java
backend/src/main/java/com/example/backend/common/response/JsonResult.java
backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
backend/src/test/java/com/example/backend/auth/config/security/SecurityConfigTest.java
backend/src/test/java/com/example/backend/common/exception/GlobalExceptionHandlerTest.java
backend/src/test/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkControllerTest.java
backend/src/test/java/com/example/backend/study/api/controller/category/info/CategoryControllerTest.java
backend/src/test/java/com/example/backend/study/api/controller/comment/commit/CommitCommentControllerTest.java
backend/src/test/java/com/example/backend/study/api/controller/comment/study/StudyCommentControllerTest.java
backend/src/test/java/com/example/backend/study/api/controller/commit/StudyCommitControllerTest.java
backend/src/test/java/com/example/backend/study/api/controller/convention/StudyConventionControllerTest.java
backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java
backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java
backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java
backend/src/test/java/com/example/backend/study/api/event/controller/FcmControllerTest.java
backend/src/test/java/com/example/backend/study/api/event/controller/NoticeControllerTest.java

#403 
현재 모든 응답(실패와 성공 관계없이) 전부 HttpStatus가 OK이고, 그 안의 Body인 커스텀 응답 객체 JsonResult의 res_code와 res_msg를 통해 성공, 실패를 판단하고 있어서 프론트 단에서 토큰 관련 재발급 처리가 어려운 상황
성공 시에는 기존의 커스텀 객체를 사용하도록 두고, 실패를 했을 경우 ResponseEntity를 사용해 HttpStatus를 변경해준다.
토큰 관련 인증 실패(JwtException) -> HttpStatus.UNAUTHORIZED
그 외의 실패 -> HttpStatus.BAD_REQUEST
ResponseEntity의 HttpStatus를 적용하면서 JsonResult의 res_code는 의미가 중복되어 삭제하였습니다!

[BE] Refactor(#403): 응답 객체 구조 변경

---

backend/src/main/java/com/example/backend/auth/config/security/SecurityConfig.java
backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
backend/src/main/java/com/example/backend/common/exception/webhook/WebhookException.java
backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepository.java
backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryCustom.java
backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryImpl.java
backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryCustom.java
backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryImpl.java
backend/src/main/java/com/example/backend/domain/define/study/todo/mapping/repository/StudyTodoMappingRepository.java
backend/src/main/java/com/example/backend/domain/define/study/todo/mapping/repository/StudyTodoMappingRepositoryCustom.java
backend/src/main/java/com/example/backend/domain/define/study/todo/mapping/repository/StudyTodoMappingRepositoryImpl.java
backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepository.java
backend/src/main/java/com/example/backend/webhook/api/controller/WebhookController.java
backend/src/main/java/com/example/backend/webhook/api/controller/request/WebhookPayload.java
backend/src/main/java/com/example/backend/webhook/api/service/WebhookService.java
backend/src/test/java/com/example/backend/auth/api/service/jwt/JwtServiceTest.java
backend/src/test/java/com/example/backend/auth/config/fixture/UserFixture.java
backend/src/test/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryTest.java
backend/src/test/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryTest.java
backend/src/test/java/com/example/backend/domain/define/study/todo/StudyTodoFixture.java
backend/src/test/java/com/example/backend/domain/define/study/todo/mapping/repository/StudyTodoMappingRepositoryTest.java
backend/src/test/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryTest.java
backend/src/test/java/com/example/backend/study/api/service/commit/StudyCommitServiceTest.java
backend/src/test/java/com/example/backend/webhook/api/controller/WebhookControllerTest.java
backend/src/test/java/com/example/backend/webhook/api/service/WebhookServiceTest.java

#431 
- 웹훅 api 시큐리티 전부 허용
- 웹훅 데이터 처리 로직 구현
처음에는 단계별로 메서드 분리해서 하려고 했는데 겹치는 조회 쿼리가 많아서 그냥 미리다 조회해두고 단계별로 했어요
이전 로직은 한방에 여러 커밋들을 가져와서 처리했다면 이번엔 커밋마다 하나하나 실시간으로 처리해줘야 하니 쿼리를 더 잘 짜야할 거 같은데 방법을 잘 모르겠네요 🥲 더 나은 방법 있으면 피드백 주세요~
---
투두 매핑 업데이트 시 한 투두에 대해 같은 사람이 다른 풀이법으로 2개의 커밋을 날렸을 시 첫 번째 커밋을 기준으로 지각 여부를 판단하도록 설정했어요.
---
투두 지각 기준이 조금 애매해요. 지금은 커밋 날리면 커밋 날린 시점을 기준으로 지각 여부를 바로 업데이트하고 있는데
커밋 승인/거절 여부에 따라 달라져야 하나 싶기도 하네요
ex) 커밋 승인 대기 상태에서 승인되면 그 때 커밋 시간을 기준으로 지각여부 판단 
- 팀장이 승인해줄 때까지 커밋했는데도 투두 완료 여부(지각 여부) 업데이트 안됨 -> 팀장 부담
만약 커밋 디폴트 상태를 승인으로 한다면?
- 커밋 발생시 바로 지각 여부를 업데이트하고 승인이 거절로 바뀔 시 지각 여부 초기화
- 근데 이것도 뭔가 이상한 느김

[BE] feat(#431): 웹 훅 데이터를 활용한 커밋 처리 로직 구현

---

backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
backend/src/main/java/com/example/backend/common/exception/github/GithubApiTokenException.java
backend/src/main/java/com/example/backend/domain/define/study/github/GithubApiToken.java
backend/src/main/java/com/example/backend/domain/define/study/github/repository/GithubApiTokenRepository.java
backend/src/main/java/com/example/backend/study/api/service/github/GithubApiService.java
backend/src/main/java/com/example/backend/study/api/service/github/GithubApiTokenService.java
backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
backend/src/test/java/com/example/backend/domain/define/study/github/GithubApiTokenFixture.java
backend/src/test/java/com/example/backend/domain/define/study/github/repository/GithubApiTokenRepositoryTest.java
backend/src/test/java/com/example/backend/study/api/service/github/GithubApiServiceTest.java
backend/src/test/java/com/example/backend/study/api/service/github/GithubApiTokenServiceTest.java
backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java

#457 
사용자별 로그인 시 얻은 Github api Token을 레디스에 저장해 필요할 때 꺼내쓸 수 있도록 구현했습니다.
Github Api 토큰 재발급 로직은 다음 이슈에서 처리하겠습니다~
---
테스트에서 레포지토리 사용한 후 꼭 tearDown에서 지워주세요!

[BE] feat(#457): 사용자별 GitHub api 토큰 관리 로직 구현

---

backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java
backend/src/main/java/com/example/backend/study/api/service/github/GithubApiService.java
backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java
backend/src/test/java/com/example/backend/study/api/service/github/GithubApiServiceTest.java
backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java

ex) #459 
어떤 변경 사항이 있나요?
스터디 장이 어떤 스터디원의 스터디 가입 신청을 수락했을 때 자동으로 스터디 레포지토리에 스터디원이 collaborator로 추가된다.
---
**1. 영민(스터디장) 회원가입**
<br>
**2. 스터디 생성**
<br>
**3. 스터디 생성 결과**
```
studyInfoId = 150
```
<br>
**4. 주성(스터디원) 회원가입**
<br>
**5. 스터디 신청** 
```
주성이가 150번 스터디에  가입신청 한다.
```
<br>
**6. 스터디 가입 신청 대기**
```
맨 오른쪽에 STUDY_WAITING -> 신청 대기 중라는 뜻
```
<br>
**7. 스터디 가입신청 수락**
```
영민이가 주성이의 스터디 가입신청을 수락한다.
```
<br>
**8. 최종 결과**
1. yml 파일 변경되었습니다. (07/27)
2. 테스트 코드 작성이 불가능한 것들은 주석처리해두었습니다.
놓친 점 피드백 부탁드립니다.

[BE] feat(#459) collaborator 초대 및 수락 자동화 구현

---

backend/src/main/java/com/example/backend/auth/api/service/rank/RankingService.java
backend/src/main/java/com/example/backend/auth/api/service/rank/response/StudyRankingResponse.java
backend/src/main/java/com/example/backend/domain/define/rank/StudyRanking.java
backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java
backend/src/test/java/com/example/backend/auth/api/service/rank/RankingServiceTest.java
backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java
backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java

#472 
어떤 변경 사항이 있나요?
유저 랭킹 시스템과 마찬가지로 실제 객체사용해서 실제로 저장하는지, 정렬되는지, 랭킹반환잘 되는지 확인해보고 모의객체 테스트는 따로 구현하지 않았슴다,, 아래사진이 실제객체사용한 테스트 결과입니다.
1. 스터디 점수 저장 테스트
2. 특정스터디 점수 업데이트
3. 특정스터디 랭킹 조회 (null일 경우도 테스트)
원래는 스터디조회에 rank 필드를 넣어주려 시도해보았지만 queryDSL도 그렇고 대공사가 될것 같아서 스터디랭킹은 호출하는 api를 따로 구현했습니다!

[BE] feat(#472): 스터디 랭킹 시스템

---

backend/src/main/java/com/example/backend/domain/define/study/info/event/ApplyApproveRefuseMemberEvent.java
backend/src/main/java/com/example/backend/domain/define/study/member/event/NotifyLeaderEvent.java
backend/src/main/java/com/example/backend/domain/define/study/member/event/NotifyMemberEvent.java
backend/src/main/java/com/example/backend/domain/define/study/member/event/ResignMemberEvent.java
backend/src/main/java/com/example/backend/domain/define/study/member/event/WithdrawalMemberEvent.java
backend/src/main/java/com/example/backend/domain/define/study/todo/event/TodoRegisterMemberEvent.java
backend/src/main/java/com/example/backend/domain/define/study/todo/event/TodoUpdateMemberEvent.java
backend/src/main/java/com/example/backend/study/api/event/service/NoticeService.java
backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java

#508 
어떤 변경 사항이 있나요?
프론트 요청사항에 따라 알림 전체를 불러오는 api에 studyInfoId를 반환하도록 추가한다.
GET(/notice)
: 여기에서 모든 알림이 study_info_id 반환하도록 하는 필드 필요 → 알림 클릭했을 때, 해당 스터디로 이동하도록 하는 기능 구현하기 위해 필요함

[BE] refactor(#508): 알림 전체 목록 api 필드 추가

---

backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryImpl.java
backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoDetailResponse.java
backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java

ex) #510
어떤 변경 사항이 있나요?
1. 스터디 가입 신청했을 때, 팀장이 승인 전인데 사용자 마이스터디에 등록되어있음
>팀장 승인 전 까지는 마이스터디에서 조회하지 못하도록 처리
<br>
2. GET:/study/{studyInfoId}에 현재 스터디에 가입 신청되어있는지 여부 확인하는 필드 추가
>프론트 단에서 권한 설정을 위해 필요
```
{
"id": 0,
"user_id": 0,
"topic": "string",
"score": 0,
"info": "string",
"maximum_member": 0,
"current_member": 0,
"last_commit_day": "2024-08-11",
"profile_image_url": "string",
"period_type": "STUDY_PERIOD_EVERYDAY",
"status": "STUDY_PUBLIC",
"created_date_time": "2024-08-11T01:14:43.530Z",
"modified_date_time": "2024-08-11T01:14:43.530Z",
"category_names": [
"string"
],
"repository_info": {
"owner": "string",
"name": "string",
"branch_name": "string"
},
"is_leader": true,
"is_waiting": true
}
```
<br>
3. GET:/study/{studyInfoId}에 …

[BE] refactor(#510) 스터디 가입 신청 로직 관련 이슈 수정

---

backend/src/main/java/com/example/backend/domain/define/study/commit/StudyCommit.java
backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepository.java
backend/src/main/java/com/example/backend/webhook/api/controller/request/CommitPayload.java
backend/src/main/java/com/example/backend/webhook/api/controller/request/WebhookPayload.java
backend/src/main/java/com/example/backend/webhook/api/service/WebhookService.java
backend/src/test/java/com/example/backend/domain/define/study/commit/StudyCommitFixture.java
backend/src/test/java/com/example/backend/domain/define/study/todo/StudyTodoFixture.java
backend/src/test/java/com/example/backend/webhook/api/service/WebhookServiceTest.java

#542 
1. push 이벤트 발생하면 등록된 웹훅으로 전송
2. 커밋 정보 받아와서 커밋, 투두 정보 업데이트
3. 스터디장에게 알림
1. push 이벤트 발생하면 등록된 웹훅으로 전송
2. 커밋 페이로드 리스트를 받는다. 각 페이로드에는 등록 파일 리스트가 들어있다.
- 삭제의 경우는 고려하지 않았다.
3. 커밋 페이로드 리스트를 순회하면서 아래 과정을 반복한다.
1. 페이로드 안 등록/수정 리스트의 파일 경로에서 투두 폴더 이름을 Set으로 추출한다.
2. 폴더 이름 Set을 돌면서 투두, 사용자를 특정한 후 권한 검증을 거쳐 커밋, 투두 매핑 정보를 업데이트한다.
- 이미 완료한 투두의 새로운 커밋이라도 투두 매핑 업데이트가 필요할 수 있다. (이전 커밋보다 푸시 시점은 늦어도 실제 커밋 시점이 빠를 수 있으므로)
- `지각했던_투두에_다시_커밋했을_때_커밋_시점이_마감일_전이라면_투두매핑_완료상태로_업데이트`
- `지각했던_투두에_다시_커밋했을_때_커밋_시점이_마감일_후라면_투두매핑_변경없음`
- `하나의_커밋에_여러개의_투두를_묶어서_푸시한_경우_해당하는_투두에_적용해야_한다`
- 마음같아선 커밋 단위를 투두로 해달라고 하고 싶지만 “밀린 숙제 제출합니다” 처럼 묶어서 커밋하는 경우가 분명 있을 것 같네요
- `하나의_푸시에_여러개의_커밋리스트가_페이로드로_전송되어도_전부_처리되어야_한다`
웹훅 푸시 이벤트 중 commits가 비어있는 경우는 브랜치가 삭제되었을 때 발생하는 이벤트라고 하니 따로 웹훅 처리 API 호출해주지 않으셔도 …

[BE] refactor(#542) webhook 처리 로직 수정

---

webhooks/src/main/kotlin/site/gitudy/webhooks/infrastructure/gitudy/WebhookClient.kt

#557 
webhooks에서 /webhook/commit 을 호출할 때 경로를 찾지 못하는 문제가 발생했습니다.
없는 경로로 호출했을 때 발생하는 에러가 나타났습니다.
localhost로 지정해도 호스트 머신의 8080 포트로 인식하지 못하고 있는 것 같습니다.
같은 네트워크로 묶여있으므로 백엔드 컨테이너 이름을 명시적으로 적어서 시도해보겠습니다.

[BE] refactor(#557): 백엔드 호출 url 수정

---

backend/src/main/java/com/example/backend/auth/config/security/filter/JwtAuthenticationFilter.java
backend/src/main/java/com/example/backend/webhook/api/service/WebhookService.java
backend/src/test/java/com/example/backend/webhook/api/service/WebhookServiceTest.java

#559 
- 투두 폴더 생성 커밋까지 등록되는 문제 해결
- 투두 폴더 생성 커밋 구분 단계
1. 페이로드의 커밋이 1개여야 한다.
2. 그 1개의 커밋에 추가된 파일이 1개이면서 수정된 파일이 없어야 한다.
3. 추가된 파일 1개가 .md의 확장자(마크다운 파일) 이어야 한다.
- JWT 인증 성공 로그 삭제
JWT 인증 성공 로그가 너무 많이 찍혀서 로그를 보기 힘들어서 삭제했습니닷
(이제 인증 실패 시에만 실패 로그가 찍힙니다)
피드백 주세요~

[BE] refactor(#559): 투두 폴더 생성 커밋까지 등록되는 문제 해결

---

backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryImpl.java

#594 
쿼리 인덱스 테스트 도중 Todo 리스트 조회 시 엄청난 양의 쿼리가 출력되는 것을 확인했다.
**Todo 리스트 조회 로직은 다음과 같다**
1. Todo 리스트 조회
2. Todo에 해당하는 Commit 조회
3. Commit 작성자 User 조회
10개의 Commit이 있는 Todo 5개를 조회하면 발생하는 쿼리 수는 다음과 같다.
- Todo 리스트 조회 1개
- Commit 리스트 조회 1개
- Commit 마다 User 조회 50개 (5*10)
총 52개의 쿼리가 발생한다;;
처음에는 User 정보까지 조회하진 않았는데 중간에 User 정보까지 필요하게 되어 추가했을 때 실수했던 것 같다. (아마 지피티 그대로 옮긴듯^)
**수정 후**
- Todo 리스트 조회 1개
- Commit + User 리스트 조회 1개
2개의 쿼리만 발생한다.
피드백 주세욧

[BE] refactor(#594): 비효율적인 todo 조회 쿼리 수정

---

backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepository.java
backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
backend/src/test/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryTest.java
backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java

#626
todo 진행률 api 해당하는 todo가 없을 경우 에러가 아닌 null 반환
문제 생기면 바로 알려주세요!

[BE] refactor: todo 진행률 api 해당하는 todo가 없을 경우 에러가 아닌 null 반환
