DKU-Dgaja/gitudy

README.md
=> docs: 홍찬희 프로필 수정

README.md
=> docs: 구영민 프로필 수정

README.md
=> [ALL] refactor(#6): README 프로필 수정

README.md
#8 
어떤 변경 사항이 있나요?
- 프로필 이미지 클릭시 깃허브로 이동할 수 있도록 링크를 삽입했습니다.
- 이주성 프로필 이미지 업데이트 했습니다.
- 코드 정렬 적용했습니다.
=> Refactor(#8) readme update leejs

README.md
#25
어떤 변경 사항이 있나요?
README.md 파일에 디자이너 이름과 사진을 추가하였습니다.
👍
=> [ALL] refactor(#25): README 프로필 수정

backend/src/main/java/com/example/backend/common/exception/GlobalExceptionHandler.java, backend/src/test/java/com/example/backend/common/exception/GlobalExceptionHandlerTest.java
#27 
어떤 변경 사항이 있나요?
* 데이터 바인딩시 발생하는 BindException 처리
* @Valid 유효성 검사 실패시 발생하는 MethodArgumentNotValidException 처리
* Exception 처리
전역적으로 처리해야 할 예외가 더 있을까요??
=> Feat(#27) global excpetion handler

backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java, backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java, backend/src/main/java/com/example/backend/auth/api/service/jwt/JwtToken.java, backend/src/main/java/com/example/backend/auth/api/service/oauth/OAuthService.java, backend/src/main/java/com/example/backend/auth/api/service/oauth/adapter/github/GithubAdapter.java, backend/src/main/java/com/example/backend/auth/api/service/oauth/builder/github/GithubURLBuilder.java, backend/src/main/java/com/example/backend/domain/define/user/User.java, backend/src/main/java/com/example/backend/external/config/ExternalClientsPostProcessor.java, backend/src/test/java/com/example/backend/auth/TestConfig.java, backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java, backend/src/test/java/com/example/backend/auth/api/service/oauth/OAuthServiceTest.java
#31 
어떤 변경 사항이 있나요?
**Refresh Token 발급 로직은 새로운 이슈에서 처리할 예정입니다~**
=> [BE] feat(#31): JWT 토큰 발급 로직 구현

backend/src/main/java/com/example/backend/auth/api/service/oauth/OAuthService.java, backend/src/main/java/com/example/backend/auth/api/service/oauth/adapter/google/GoogleAdapter.java, backend/src/main/java/com/example/backend/auth/api/service/oauth/builder/google/GoogleURLBuilder.java, backend/src/main/java/com/example/backend/external/clients/oauth/google/GoogleProfileClients.java, backend/src/main/java/com/example/backend/external/clients/oauth/google/GoogleTokenClients.java, backend/src/main/java/com/example/backend/external/clients/oauth/google/response/GoogleProfileResponse.java, backend/src/main/java/com/example/backend/external/clients/oauth/google/response/GoogleTokenResponse.java, backend/src/test/java/com/example/backend/auth/api/service/oauth/OAuthServiceTest.java, backend/src/test/java/com/example/backend/auth/api/service/oauth/adapter/google/GoogleAdapterTest.java, backend/src/test/java/com/example/backend/auth/api/service/oauth/builder/google/GoogleURLBuilderTest.java
#30 
어떤 변경 사항이 있나요?
- 구글 로그인 구현
- OAuthURLBuiler, OAuthAdapter 구현
사용하는게 아직 어색한데 피드백 부탁드립니당~~
=> [BE] feat(#30): Google OAuth2 Login 구현

backend/src/main/java/com/example/backend/auth/api/service/oauth/OAuthService.java, backend/src/main/java/com/example/backend/auth/api/service/oauth/adapter/kakao/KakaoAdapter.java, backend/src/main/java/com/example/backend/auth/api/service/oauth/builder/kakao/KakaoURLBuilder.java, backend/src/main/java/com/example/backend/external/clients/oauth/kakao/KakaoProfileClients.java, backend/src/main/java/com/example/backend/external/clients/oauth/kakao/KakaoTokenClients.java, backend/src/main/java/com/example/backend/external/clients/oauth/kakao/response/KakaoProfileResponse.java, backend/src/main/java/com/example/backend/external/clients/oauth/kakao/response/KakaoTokenResponse.java, backend/src/test/java/com/example/backend/auth/api/service/oauth/OAuthServiceTest.java, backend/src/test/java/com/example/backend/auth/api/service/oauth/adapter/kakao/KakaoAdapterTest.java, backend/src/test/java/com/example/backend/auth/api/service/oauth/builder/kakao/KakaoURLBuilderTest.java, backend/src/test/java/com/example/backend/external/clients/oauth/kakao/KakaoClientTest.java
ex) #이슈번호
어떤 변경 사항이 있나요?
* 카카오 로그인 구현
* OAuthURLBuiler, OAuthAdapter 카카오 추가 구현
* KakaoProfileResponse 카카오는 email을 받아올 수가 없습니다.
* Client Test는 추후에 업데이트
리뷰 부탁드립니다~
첫 PR이라 예쁘게 봐주세요 ㅎㅎ
=> [BE] Feat(#29): Kakao OAuth2 Login 구현

.github/workflows/CI_dev_be_pull_request.yml
ex) #이슈번호
어떤 변경 사항이 있나요?
pull request에 [BE]로 시작하는 풀리퀘스트만 빌드해줍니다.
=> [BE] chore pipeline

.github/workflows/CI_dev_be_pull_request.yml, backend/build.gradle
ex) #이슈번호
어떤 변경 사항이 있나요?
jacoco 커버리지를 추가했습니다.
=> [CI] chore jacoco coverage

.github/workflows/CI_dev_be_pull_request.yml, backend/src/test/java/com/example/backend/auth/api/service/oauth/OAuthServiceTest.java
=> [BE] refactor(#51): OAuthServiceTest 오류수정

backend/src/test/java/com/example/backend/auth/api/service/oauth/OAuthServiceTest.java, backend/src/test/java/com/example/backend/auth/api/service/oauth/adapter/kakao/KakaoAdapterTest.java
어떤 변경 사항이 있나요?
OAuthServiceTest 에러 수정
=> [BE] fix: OAuthServiceTest 에러 수정

backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java, backend/src/main/java/com/example/backend/auth/api/service/jwt/JwtService.java, backend/src/main/java/com/example/backend/auth/api/service/token/RefreshTokenService.java, backend/src/main/java/com/example/backend/domain/define/refreshToken/RefreshToken.java, backend/src/main/java/com/example/backend/domain/define/refreshToken/repository/RefreshTokenRepository.java, backend/src/test/java/com/example/backend/auth/api/service/jwt/JwtServiceTest.java, backend/src/test/java/com/example/backend/auth/api/service/token/RefreshTokenServiceTest.java, backend/src/test/java/com/example/backend/domain/define/refreshToken/repository/RefreshTokenRepositoryTest.java
ex) #이슈번호
어떤 변경 사항이 있나요?
* Refresh Token 생성 함수 추가
* Refresh Token redis에 저장
* Refresh Token 관련 테스트
피드백 부탁드립니다~~
=> [BE] feat(#47): refresh token 생성 및 저장 구현

backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java, backend/src/main/java/com/example/backend/auth/api/service/state/LoginStateService.java, backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java, backend/src/main/java/com/example/backend/common/exception/state/LoginStateException.java, backend/src/main/java/com/example/backend/domain/define/state/LoginState.java, backend/src/main/java/com/example/backend/domain/define/state/LoginStateRepository.java, backend/src/test/java/com/example/backend/domain/redis/define/state/LoginStateTest.java, backend/src/test/java/com/example/backend/external/clients/oauth/google/GoogleClientTest.java
#46 
어떤 변경 사항이 있나요?
* State 저장,검증,삭제 구현
피드백 부탁드립니다!!
=> [BE] feat(#46): state verification

backend/src/test/java/com/example/backend/auth/api/service/jwt/JwtServiceTest.java
=> Refactor(#68) generate refresh token test error 수정

backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java, backend/src/main/java/com/example/backend/auth/api/service/state/LoginStateService.java, backend/src/main/java/com/example/backend/domain/define/refreshToken/RefreshToken.java, backend/src/main/java/com/example/backend/domain/define/state/LoginState.java, backend/src/main/java/com/example/backend/domain/define/state/LoginStateRepository.java, backend/src/test/java/com/example/backend/auth/api/service/jwt/JwtServiceTest.java, backend/src/test/java/com/example/backend/auth/api/service/token/RefreshTokenServiceTest.java, backend/src/test/java/com/example/backend/domain/define/refreshToken/repository/RefreshTokenRepositoryTest.java, backend/src/test/java/com/example/backend/domain/redis/define/state/LoginStateTest.java
* platformId -> subject 수정
ex) #이슈번호
어떤 변경 사항이 있나요?
platformId -> subject 수정
=> [BE] refactor (#68): platformId -> subject 수정

backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java, backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java, backend/src/main/java/com/example/backend/auth/api/service/token/RefreshTokenService.java, backend/src/main/java/com/example/backend/auth/config/security/filter/JwtAuthenticationFilter.java, backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java, backend/src/test/java/com/example/backend/auth/TestConfig.java, backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
#61 
어떤 변경 사항이 있나요?
Logout 구현 (redis에 저장된 refreshtoken 삭제)
AuthControllerTest에서 "로그아웃 성공 테스트"
부분이 해결이 안됐는데 더 좋은 테스트 방법이 있는지 다른 해결방법이 있는지도 피드백 부탁드립미다...
=> [BE] feat(#61): logout 구현

backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java, backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java, backend/src/main/java/com/example/backend/auth/api/service/token/RefreshTokenService.java, backend/src/main/java/com/example/backend/auth/config/security/filter/JwtAuthenticationFilter.java, backend/src/test/java/com/example/backend/auth/api/service/token/RefreshTokenServiceTest.java
#79
어떤 변경 사항이 있나요?
* 패키지 경로 수정
* 쓰지 않는 import 제거
* 테스트 오류 수정
=> [BE] fix(#79): 패키지 경로 수정 

backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java, backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java, backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java, backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
=> [BE] fix(#89): resolve conflicts

backend/src/main/java/com/example/backend/auth/api/controller/auth/response/UserInfoResponse.java, backend/src/main/java/com/example/backend/domain/define/account/user/User.java, backend/src/main/java/com/example/backend/domain/define/study/commit/StudyCommit.java, backend/src/main/java/com/example/backend/domain/define/study/commit/constant/LikeCount.java, backend/src/main/java/com/example/backend/domain/define/study/todo/info/StudyTodo.java, backend/src/test/java/com/example/backend/auth/TestConfig.java, backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java, backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java, backend/src/test/java/com/example/backend/domain/define/study/commit/constant/LikeCountTest.java
#91 
어떤 변경 사항이 있나요?
데이터베이스 설계 수정
커밋 뿐만 아니라 혹시 나중에 다른 엔티티에서 좋아요 필드가 사용될 수 있을 거 같아 일단 @Embedded로 설계했습니다. 별로인 것 같으면 의견 주세요!
=> [BE] refactor(#91): 데이터베이스 설계 수정

backend/src/main/java/com/example/backend/auth/api/controller/auth/response/UserInfoResponse.java, backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java, backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java, backend/src/main/java/com/example/backend/common/exception/bookmark/BookmarkException.java, backend/src/main/java/com/example/backend/domain/define/account/bookmark/repository/StudyBookmarkRepository.java, backend/src/main/java/com/example/backend/domain/define/account/bookmark/repository/StudyBookmarkRepositoryCustom.java, backend/src/main/java/com/example/backend/domain/define/account/bookmark/repository/StudyBookmarkRepositoryImpl.java, backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepository.java, backend/src/main/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkController.java, backend/src/main/java/com/example/backend/study/api/controller/bookmark/response/BookmarkInfoListAndCursorIdxResponse.java, backend/src/main/java/com/example/backend/study/api/service/bookmark/StudyBookmarkService.java, backend/src/main/java/com/example/backend/study/api/service/bookmark/response/BookmarkInfoResponse.java, backend/src/main/java/com/example/backend/study/api/service/info/response/StudyInfoResponse.java, backend/src/main/java/com/example/backend/study/api/service/info/response/StudyInfoWithIdResponse.java, backend/src/test/java/com/example/backend/auth/TestConfig.java, backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java, backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java, backend/src/test/java/com/example/backend/auth/api/service/oauth/OAuthServiceTest.java, backend/src/test/java/com/example/backend/auth/config/fixture/UserFixture.java, backend/src/test/java/com/example/backend/common/utils/TokenUtil.java, backend/src/test/java/com/example/backend/domain/define/account/bookmark/StudyBookmarkFixture.java, backend/src/test/java/com/example/backend/domain/define/account/bookmark/repository/StudyBookmarkRepositoryTest.java, backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java, backend/src/test/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/bookmark/StudyBookmarkServiceTest.java
#101  #106 
어떤 변경 사항이 있나요?
- Test Fixture 구조 수정
- 커서 페이지네이션 기반 북마크 조회 api 구현
- 북마크가 이미 등록되어 있으면 삭제하고 미등록 상태면 등록하는 api 구현
놓친 부분 있으면 알려주세요!
=> [BE] feat(#106): 북마크 목록 조회 & 등록/삭제 api 구현

backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepository.java, backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryCustom.java, backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryImpl.java, backend/src/test/java/com/example/backend/domain/define/study/member/StudyMemberFixture.java, backend/src/test/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryTest.java
#118 
어떤 변경 사항이 있나요?
- 활동중인 스터디원인지 판단하는 로직
- 스터디장인지 판단하는 로직

공통으로 사용될만한 로직 추가해야할 것 있으면 말해주세요!
=> [BE] feat(#118): StudyMember 권한 검증 관련 공통 로직 구현

backend/src/main/java/com/example/backend/auth/api/controller/auth/request/AuthRegisterRequest.java, backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
#125
어떤 변경 사항이 있나요?
@JsonProperty제거 후 모든 테스트 통과했습니다~!
=> Refactor(#125) @json property 제거

backend/src/main/java/com/example/backend/auth/config/ProjectConfig.java, backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java, backend/src/main/java/com/example/backend/common/exception/member/MemberException.java, backend/src/main/java/com/example/backend/common/exception/todo/TodoException.java, backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepository.java, backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryCustom.java, backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryImpl.java, backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoMappingRepository.java, backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepository.java, backend/src/main/java/com/example/backend/study/api/controller/todo/StudyTodoController.java, backend/src/main/java/com/example/backend/study/api/controller/todo/request/StudyTodoRequest.java, backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java, backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java, backend/src/test/java/com/example/backend/auth/config/fixture/UserFixture.java, backend/src/test/java/com/example/backend/domain/define/study/member/StudyMemberFixture.java, backend/src/test/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryTest.java, backend/src/test/java/com/example/backend/domain/define/study/todo/StudyTodoFixture.java, backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
#117
어떤 변경 사항이 있나요?
Todo api 구현
- Todo 등록 컨트롤러, 서비스 구현
- Todo 등록 컨트롤러, 서비스 테스트 구현
피드백 부탁드립니다!! 👍 
스터디에 속한 스터디원 조회가아니라 활동중인 스터디원을 조회해야하나 생각드네요 음,,
=> [BE] feat(#117): Todo 등록 api 구현

backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java, backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoMappingRepository.java, backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepository.java, backend/src/main/java/com/example/backend/study/api/controller/todo/StudyTodoController.java, backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java, backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
#123 
어떤 변경 사항이 있나요?
Todo 삭제 api 구현
스터디장만 Todo 삭제가능하도록 구현했습니다!
피드백 부탁드립니다!
=> [BE] feat(#123): Todo 삭제 api

backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java, backend/src/main/java/com/example/backend/common/exception/comment/study/StudyCommentException.java, backend/src/main/java/com/example/backend/domain/define/study/comment/study/repository/StudyCommentRepository.java, backend/src/main/java/com/example/backend/study/api/controller/comment/study/StudyCommentController.java, backend/src/main/java/com/example/backend/study/api/controller/comment/study/request/StudyCommentRegisterRequest.java, backend/src/main/java/com/example/backend/study/api/service/comment/study/StudyCommentService.java, backend/src/test/java/com/example/backend/domain/define/study/comment/StudyCommentFixture.java, backend/src/test/java/com/example/backend/study/api/controller/comment/study/StudyCommentControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/comment/study/StudyCommentServiceTest.java
ex) #140 
어떤 변경 사항이 있나요?
스터디 댓글 등록 api 구현
특이사항 없습니다!
피드백 부탁드립니다~~
=> Feat(#140)   스터디 댓글 등록 api 구현

backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java, backend/src/main/java/com/example/backend/domain/define/study/comment/study/StudyComment.java, backend/src/main/java/com/example/backend/study/api/controller/comment/study/StudyCommentController.java, backend/src/main/java/com/example/backend/study/api/controller/comment/study/request/StudyCommentUpdateRequest.java, backend/src/main/java/com/example/backend/study/api/service/comment/study/StudyCommentService.java, backend/src/test/java/com/example/backend/domain/define/study/comment/StudyCommentFixture.java, backend/src/test/java/com/example/backend/study/api/controller/comment/study/StudyCommentControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/comment/study/StudyCommentServiceTest.java
ex) #144
어떤 변경 사항이 있나요?
스터디 댓글 수정 api 구현
스터디 댓글 수정 api 테스트
새벽에 잠이 안와서 했네요 ㅎㅎ
피드백 부탁드립니다~!
=> [BE] feat: (#144) 스터디 댓글 수정 api

backend/src/main/java/com/example/backend/domain/define/study/commit/StudyCommit.java, backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/service/commit/response/CommitInfoResponse.java, backend/src/test/java/com/example/backend/domain/define/study/commit/StudyCommitFixture.java, backend/src/test/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepositoryTest.java, backend/src/test/java/com/example/backend/study/api/service/comment/commit/CommitCommentServiceTest.java, backend/src/test/java/com/example/backend/study/api/service/commit/StudyCommitServiceTest.java
#150 
어떤 변경 사항이 있나요?
커밋이 속한 투두 정보를 저장할 필드 추가
=> [BE] refactor(#150): STUDYCOMMIT 데이터베이스 수정

backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryCustom.java, backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java, backend/src/main/java/com/example/backend/study/api/controller/member/response/StudyMembersResponse.java, backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java, backend/src/test/java/com/example/backend/auth/config/fixture/UserFixture.java, backend/src/test/java/com/example/backend/domain/define/study/member/StudyMemberFixture.java, backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
#147 
스터디에 속한 스터디원 조회 api
스터디에 속한 스터디원 조회 api
스터디원 조회 기여도별로 정렬api 입니다.
피드백 부탁드립니다!
=> [BE] feat(#147): 스터디에 속한 스터디원 조회 api

backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java, backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
#153 
swagger 미적용 수정
swagger 미적용 수정
logout GetMapping 보단 PostMapping이 맞는거 같아서  추가로 수정했습니다!
=> [BE] refactor(#153): swagger 미적용 수정

backend/src/main/java/com/example/backend/study/api/controller/comment/study/StudyCommentController.java, backend/src/main/java/com/example/backend/study/api/service/comment/study/StudyCommentService.java, backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java, backend/src/test/java/com/example/backend/study/api/controller/comment/study/StudyCommentControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/comment/study/StudyCommentServiceTest.java
ex) #146
어떤 변경 사항이 있나요?
스터디 댓글 삭제 api 구현
리뷰 부탁드립니다~!
=> [BE] feat(#146) :  스터디 댓글 삭제 api 구현

backend/src/test/java/com/example/backend/study/api/controller/convention/StudyConventionControllerTest.java
#165 
어떤 변경 사항이 있나요?
isValidateMember 메서드 반환 테스트 수정입니다
=> [BE] fix(#165): 테스트 오류해결

backend/src/main/java/com/example/backend/domain/define/study/member/StudyMember.java, backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepository.java, backend/src/main/java/com/example/backend/domain/define/study/todo/mapping/repository/StudyTodoMappingRepository.java, backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryCustom.java, backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java, backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java, backend/src/test/java/com/example/backend/domain/define/study/todo/StudyTodoFixture.java, backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
#152 
어떤 변경 사항이 있나요?
스터디원 강퇴 api
스터티 탈퇴 api
따로 삭제하는 것 없이 멤버의 상태만 변경해주도록 구현했습니다~
=> [BE] feat(#152): 스터디원 강퇴, 스터디 탈퇴 api

backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java, backend/src/main/java/com/example/backend/common/exception/convention/ConventionException.java, backend/src/main/java/com/example/backend/domain/define/study/convention/StudyConvention.java, backend/src/main/java/com/example/backend/study/api/controller/convention/StudyConventionController.java, backend/src/main/java/com/example/backend/study/api/controller/convention/request/StudyConventionRequest.java, backend/src/main/java/com/example/backend/study/api/controller/convention/request/StudyConventionUpdateRequest.java, backend/src/main/java/com/example/backend/study/api/service/convention/StudyConventionService.java, backend/src/test/java/com/example/backend/domain/define/study/convention/StudyConventionFixture.java, backend/src/test/java/com/example/backend/study/api/controller/convention/StudyConventionControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/convention/StudyConventionServiceTest.java, backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
#167 
어떤 변경 사항이 있나요?
컨벤션 등록 url 조정
컨벤션 수정, 삭제 api 구현
컨벤션 삭제 부분 피그마는 따로 없는거같네용!
피드백 부탁드립니다~~
=> [BE] feat(#167): 컨벤션 수정, 삭제 api

backend/src/main/java/com/example/backend/domain/define/study/convention/repository/StudyConventionRepository.java, backend/src/main/java/com/example/backend/domain/define/study/convention/repository/StudyConventionRepositoryCustom.java, backend/src/main/java/com/example/backend/domain/define/study/convention/repository/StudyConventionRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/controller/convention/StudyConventionController.java, backend/src/main/java/com/example/backend/study/api/controller/convention/response/StudyConventionListAndCursorIdxResponse.java, backend/src/main/java/com/example/backend/study/api/controller/convention/response/StudyConventionResponse.java, backend/src/main/java/com/example/backend/study/api/service/convention/StudyConventionService.java, backend/src/test/java/com/example/backend/domain/define/study/convention/StudyConventionFixture.java, backend/src/test/java/com/example/backend/domain/define/study/convention/repository/StudyConventionRepositoryTest.java, backend/src/test/java/com/example/backend/study/api/controller/convention/StudyConventionControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/convention/StudyConventionServiceTest.java
#174 
어떤 변경 사항이 있나요?
컨벤션 조회 api
컨벤션 전체조회도 혹시몰라 페이지네이션으로 작성했습니다.. 피드백 부탁드립니다!!
=> [BE] feat(#174): 컨벤션 조회 api

backend/src/main/java/com/example/backend/domain/define/study/member/constant/StudyMemberStatus.java
* 대기중, 거절 필드 추가
#181 
ex) #이슈번호
어떤 변경 사항이 있나요?
스터디 멤버 상태 수정
대기, 거절 필드 추가
=> [BE] refactor(#181): 스터디 멤버 상태 수정

backend/src/main/java/com/example/backend/auth/api/controller/auth/request/AuthRegisterRequest.java, backend/src/main/java/com/example/backend/auth/api/controller/auth/response/AuthLoginResponse.java, backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
ex) #이슈번호
어떤 변경 사항이 있나요?
회원가입 DTO 수정
=> [BE] refactor(#176): 회원가입 DTO 수정

backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryCustom.java, backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java, backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoListAndCursorIdxResponse.java, backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoListResponse.java, backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java, backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java, backend/src/test/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryTest.java, backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
ex) #172 
어떤 변경 사항이 있나요?
1. 커서기반 페이지네이션
2. 최신순, 활동순, 랭킹순 정렬
3. 전체 스터디 목록 조회 api 구현
4. 전체 스터디 목록 조회 api 테스트 구현
리뷰 부탁드립니다~!
=> [BE] feat(#172): 전체 스터디 목록 조회 api 구현

backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
#176 
어떤 변경 사항이 있나요?
role값이 내려가지 않는 문제 해결
=> [BE] refactor(#176): role값이 내려가지 않는 문제 해결

backend/build.gradle, backend/src/main/java/com/example/backend/auth/config/ProjectConfig.java
ex) #191
* ModelResolver 추가
* swagger version update
=> [BE] refactor(#191): Swagger-ui snake case 변환

backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java, backend/src/main/java/com/example/backend/domain/define/study/member/StudyMember.java, backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryCustom.java, backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java, backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java, backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java, backend/src/test/java/com/example/backend/domain/define/study/member/StudyMemberFixture.java, backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
#178 
어떤 변경 사항이 있나요?
일단 알림 메서드를 제외하고 가입 신청 api만 구현해보았습니다. 피드백 부탁드려요!
=> [BE] feat(#178): 스터디 가입 신청 api

backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java, backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoDetailResponse.java, backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java, backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java, backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
ex) #185 
어떤 변경 사항이 있나요?
스터디 상세정보 api 구현
1. 스터디 정보 포함
2. 카테고리 id 리스트 포함
사진에서 동그라미 제외 부분은 이미 존재하는 api입니다!
=> [BE] feat(#185): 스터디 상세정보 api 구현

backend/src/main/java/com/example/backend/domain/define/study/category/info/repository/StudyCategoryRepositoryCustom.java, backend/src/main/java/com/example/backend/domain/define/study/category/info/repository/StudyCategoryRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java, backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoDetailResponse.java, backend/src/main/java/com/example/backend/study/api/controller/info/response/UpdateStudyInfoPageResponse.java, backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java, backend/src/test/java/com/example/backend/domain/define/study/category/mapping/repository/StudyCategoryMappingRepositoryTest.java, backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java, backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
ex) #196
어떤 변경 사항이 있나요?
DTO에서 아이디 리스트를 반환하는 것을 name 리스트로 변경
1. 스터디 정보 수정 페이지 response DTO 수정
2. 스터디 상세 정보 페이지 response DTO 수정
피드백 부탁드립니다!
=> [BE] refactor(#196): category id list 반환 -> category name list 반환

android/gitudy/data/src/main/java/com/takseha/data/api/github/GithubApi.kt, android/gitudy/data/src/main/java/com/takseha/data/api/github/RetrofitInstance.kt, android/gitudy/data/src/main/java/com/takseha/data/dto/auth/register/GithubIdResponse.kt, android/gitudy/data/src/main/java/com/takseha/data/repository/GithubRepository.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/login/InputIdFragment.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/login/RegisterCompleteFragment.kt, android/gitudy/presentation/src/main/res/anim/alpha.xml, android/gitudy/presentation/src/main/res/anim/fade_in.xml, android/gitudy/presentation/src/main/res/layout/fragment_input_id.xml, android/gitudy/presentation/src/main/res/layout/fragment_register_complete.xml, android/gitudy/presentation/src/main/res/values/strings.xml
#195
어떤 변경 사항이 있나요?
깃허브 api를 호출하여 유저가 입력한 github id가 github에 등록되어 있는지 체크하는 로직을 구현하였다.
=> [AN] refactor(#195): 유저 연동 깃허브 아이디 유효성 검증 기능 수정

backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java, backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java, backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
#184 
어떤 변경 사항이 있나요?
스터디장의 가입신청 승인/거부
승인 -> 활동으로 상태변경
거부 -> 거부로 상태변경
추후 알림메서드 추가 예정입니다
=> [BE] feat(#184): 스터디장의 가입신청 승인/거부

backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java, backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java, backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java, backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
#203 
어떤 변경 사항이 있나요?
스터디 가입 신청 취소 api
피드백 부탁드립니다~
=> [BE] feat(#203): 스터디 가입 신청 취소 api

backend/src/main/java/com/example/backend/study/api/controller/category/info/CategoryController.java, backend/src/main/java/com/example/backend/study/api/controller/category/info/request/CategoryRegisterRequest.java, backend/src/main/java/com/example/backend/study/api/service/category/info/CategoryService.java, backend/src/test/java/com/example/backend/study/api/controller/category/info/CategoryControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/category/info/CategoryServiceTest.java
ex) #201 
어떤 변경 사항이 있나요?
카테고리 등록 api 구현 
스터디 개설할 때 기본적으로 존재하는 카테고리가 있고 원하면 추가할 수 있는 방식으로 카테고리를 구현하려고 합니다!
특이사항 없습니다!
=> [BE] feat(#201): category 등록 api

backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java, backend/src/main/java/com/example/backend/common/exception/category/CategoryException.java, backend/src/main/java/com/example/backend/domain/define/study/category/info/StudyCategory.java, backend/src/main/java/com/example/backend/study/api/controller/category/info/CategoryController.java, backend/src/main/java/com/example/backend/study/api/controller/category/info/request/CategoryUpdateRequest.java, backend/src/main/java/com/example/backend/study/api/service/category/info/CategoryService.java, backend/src/test/java/com/example/backend/study/api/controller/category/info/CategoryControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/category/info/CategoryServiceTest.java
ex) #207 
어떤 변경 사항이 있나요?
* 카테고리 수정, 삭제 api 구현
* 카테고리 수정, 삭제 api Test 구현
특이사항 없습니다~!
=> [BE] feat(#207): 카테고리 수정, 삭제 api 구현

backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java, backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryCustom.java, backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java, backend/src/main/java/com/example/backend/study/api/controller/member/response/StudyMemberApplyListAndCursorIdxResponse.java, backend/src/main/java/com/example/backend/study/api/controller/member/response/StudyMemberApplyResponse.java, backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java, backend/src/test/java/com/example/backend/auth/config/fixture/UserFixture.java, backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
ex) #이슈번호
#209 
어떤 변경 사항이 있나요?
스터디 가입신청 목록 조회
DTO 는 필요할거같은거는 다 넣어놨습니다.
아마 여기 팀원 관리를 누르면 목록페이지가 뜨지 않을까.. 생각하고 구현했습니다.
피드백 부탁드립니다!
=> [BE] feat(#209): 스터디 가입신청 목록 조회 api

backend/src/main/java/com/example/backend/study/api/controller/todo/StudyTodoController.java, backend/src/main/java/com/example/backend/study/api/controller/todo/response/StudyTodoResponse.java, backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java, backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
ex) #이슈번호
#211 
어떤 변경 사항이 있나요?
Todo 단일 조회 api
Todo 단일 조회는 따로 안해놔서 추가했습니다!
=> [BE] feat(#211): Todo 단일 조회 api

backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java, backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java
=> [BE] refactor(#217):  required추가

backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java
=> [BE] refactor(#219) 스웨거 오류 수정

backend/src/main/java/com/example/backend/domain/define/study/category/info/repository/StudyCategoryRepositoryCustom.java, backend/src/main/java/com/example/backend/domain/define/study/category/info/repository/StudyCategoryRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/controller/category/info/CategoryController.java, backend/src/main/java/com/example/backend/study/api/controller/category/info/response/CategoryListAndCursorIdxResponse.java, backend/src/main/java/com/example/backend/study/api/service/category/info/CategoryService.java, backend/src/main/java/com/example/backend/study/api/service/category/info/response/CategoryResponse.java, backend/src/test/java/com/example/backend/domain/define/study/StudyCategory/info/StudyCategoryFixture.java, backend/src/test/java/com/example/backend/domain/define/study/category/info/repository/StudyCategoryRepositoryTest.java, backend/src/test/java/com/example/backend/study/api/controller/category/info/CategoryControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/category/info/CategoryServiceTest.java
ex) #215 
어떤 변경 사항이 있나요?
커서기반 페이지네이션 기반 카테고리 리스트 조회 api 구현
리뷰 부탁드립니다~!
=> [BE] feat(#215) 카테고리 리스트 조회 api 구현

backend/src/main/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkController.java, backend/src/main/java/com/example/backend/study/api/controller/comment/study/StudyCommentController.java, backend/src/main/java/com/example/backend/study/api/controller/commit/StudyCommitController.java, backend/src/main/java/com/example/backend/study/api/controller/convention/StudyConventionController.java, backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java, backend/src/main/java/com/example/backend/study/api/controller/todo/StudyTodoController.java, backend/src/test/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/comment/study/StudyCommentControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/commit/StudyCommitControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/convention/StudyConventionControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java
ex) #222 
어떤 변경 사항이 있나요?
cursorIdx가 null일 때를 허용하기 위해서 required = false 추가했습니다.
=> [BE] refactor(#222): required = false 추가

android/gitudy/.gitignore, android/gitudy/app/.gitignore, android/gitudy/app/build.gradle.kts, android/gitudy/data/build.gradle.kts, android/gitudy/data/src/main/AndroidManifest.xml, android/gitudy/presentation/build.gradle.kts, android/gitudy/presentation/src/main/java/com/takseha/presentation/firebase/MyFirebaseMessagingService.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/SplashActivity.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/login/SocialLoginCompleteActivity.kt
#232
어떤 변경 사항이 있나요?
알람 기능 구현을 위한 FCM 클라이언트 앱 세팅 및 포그라운드 메시지 수신 기능 구현
백그라운드 메시지 수신 기능은 추후 구현 예정입니다!!
=> [AN] chore(#232): firebase 세팅

backend/src/main/java/com/example/backend/domain/define/account/user/User.java, backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java, backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java, backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java, backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
ex) #이슈번호
어떤 변경 사항이 있나요?
회원가입, 스터디생성, 스터디 가입 시 user 점수 로직 추가
* 회원가입 시 User +10점
* 스터디 생성 시 User +5점
* 스터디 가입 시 User +5점
피드백 부탁드립니다~!
=> [BE] feat(#233): 회원가입, 스터디생성, 스터디 가입 시 user 점수 로직 추가

.github/workflows/CICD_dev_be_merge.yml, .github/workflows/CI_dev_be_pull_request.yml, backend/.gitignore, backend/build.gradle, backend/src/main/java/com/example/backend/domain/config/FirebaseConfig.java
#229 
어떤 변경 사항이 있나요?
firebase 초기 세팅
json파일 형태로 키를 resources 하위에 두고 application.yml 을 아래사진과 같이 수정했는데
로컬에서는 잘 되는데 혹시 서버도 같이 초기화해야하는건가요..? 😢
=> [BE] setting(#229): FirebaseConfig 추가

backend/src/main/java/com/example/backend/study/api/service/category/info/CategoryService.java, backend/src/main/java/com/example/backend/study/api/service/comment/commit/CommitCommentService.java, backend/src/main/java/com/example/backend/study/api/service/comment/study/StudyCommentService.java, backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java, backend/src/main/java/com/example/backend/study/api/service/convention/StudyConventionService.java, backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java, backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java, backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
ex) #238 
어떤 변경 사항이 있나요?
중복되는 예외처리 코드들을 함수화 시켜 재사용성을 증가시켰습니다.
EX)
* StudyinfoService  -> 스터디 조회 예외처리 함수 추가
* CategoryService -> 카테고리 조회 예외처리 함수 추가
* ...
* ...
놓친 점이나 더 좋은 방법 있으시면 말씀해주세요~!
playformId + platformType로 User객체를 조회하는 로직은 UserService에서 책임을 갖는게 맞는데 UserService가 존재하지 않아 StudyMemberService 안에 넣어두었습니다.
=> [BE] refactor(#238) findbyid orthrow() 중복제거

backend/src/main/java/com/example/backend/auth/api/controller/auth/request/AuthRegisterRequest.java, backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java, backend/src/main/java/com/example/backend/auth/api/service/auth/request/AuthServiceRegisterRequest.java, backend/src/main/java/com/example/backend/domain/define/account/user/User.java, backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java, backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
#258 
회원가입 DTO에 푸시 알림 동의 여부 필드를 추가했습니다.
놓친 부분 있으면 말해주세요!
=> refactor(#258): 회원가입 dto 수정

backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java, backend/src/main/java/com/example/backend/domain/define/study/info/StudyInfo.java, backend/src/main/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkController.java, backend/src/main/java/com/example/backend/study/api/controller/category/info/CategoryController.java, backend/src/main/java/com/example/backend/study/api/controller/category/info/request/CategoryRegisterRequest.java, backend/src/main/java/com/example/backend/study/api/controller/category/info/request/CategoryUpdateRequest.java, backend/src/main/java/com/example/backend/study/api/controller/comment/study/StudyCommentController.java, backend/src/main/java/com/example/backend/study/api/controller/comment/study/request/StudyCommentRegisterRequest.java, backend/src/main/java/com/example/backend/study/api/controller/comment/study/request/StudyCommentUpdateRequest.java, backend/src/main/java/com/example/backend/study/api/controller/commit/StudyCommitController.java, backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java, backend/src/main/java/com/example/backend/study/api/controller/info/request/StudyInfoRegisterRequest.java, backend/src/main/java/com/example/backend/study/api/controller/info/request/StudyInfoUpdateRequest.java, backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java, backend/src/main/java/com/example/backend/study/api/service/comment/study/StudyCommentService.java, backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java, backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java, backend/src/test/java/com/example/backend/domain/define/study/comment/StudyCommentFixture.java, backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java, backend/src/test/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/category/info/CategoryControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/comment/study/StudyCommentControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/commit/StudyCommitControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/category/info/CategoryServiceTest.java, backend/src/test/java/com/example/backend/study/api/service/comment/study/StudyCommentServiceTest.java, backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
#260 
request에서 uesrId를 받지 않고 jwt 토큰으로만 사용자의 정보 확인하도록 변경
워낙 많았어서 빼먹은 부분 있을 수도 있어요! 머지해서 사용하시다가 발견하시면 말해주세요!!!
=> refactor(#260): request에서 uesrId를 받지 않고 jwt 토큰으로만 사용자의 정보 확인하도록 변경

backend/src/main/java/com/example/backend/domain/define/study/member/StudyMember.java, backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/controller/member/response/StudyMemberApplyResponse.java, backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java, backend/src/test/java/com/example/backend/domain/define/study/info/listener/StudyEventListenerTest.java, backend/src/test/java/com/example/backend/domain/define/study/member/StudyMemberFixture.java, backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
#264 
어떤 변경 사항이 있나요?
스터디장에게 한마디 필드 생성  signGreeting
피드백 부탁드립니다~
=> [BE] refactor(#264): StudyMember 스터디장에게 한마디 필드 생성

backend/src/main/java/com/example/backend/domain/define/fcm/listener/WithdrawalMemberListener.java, backend/src/main/java/com/example/backend/domain/define/study/member/event/WithdrawalMemberEvent.java, backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java, backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java, backend/src/test/java/com/example/backend/domain/define/fcm/listener/WithdrawalMemberListenerTest.java, backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
ex) #270
어떤 변경 사항이 있나요?
스터디 탈퇴 유저가 생겼을 때 스터디장에게 알림 구현
놓친 점과 피드백 부탁드립니다~!
그리고 깃털 이모티콘 괜찮은거 있으면 댓글에 남겨주세요! 알림에 사용하려고 합니다.
=> [BE] feat(#270): 스터디 탈퇴 유저가 생겼을 때 스터디장에게 알림

backend/src/main/java/com/example/backend/domain/define/fcm/listener/NotifyMemberListener.java, backend/src/main/java/com/example/backend/domain/define/study/member/event/NotifyMemberEvent.java, backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java, backend/src/main/java/com/example/backend/study/api/controller/member/request/MessageRequest.java, backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java, backend/src/test/java/com/example/backend/domain/define/fcm/listener/NotifyMemberListenerTest.java, backend/src/test/java/com/example/backend/domain/define/study/member/MemberEventFixture.java, backend/src/test/java/com/example/backend/domain/define/study/member/StudyMemberFixture.java, backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
#272 
어떤 변경 사항이 있나요?
특정 스터디원에게 알림 전송(fcm) api 
알림테이블 구현시 로직 추가할 예정입니다~
=> [BE] feat(#272): 특정 스터디원에게 알림 전송(fcm) api

README.md
#278
어떤 변경 사항이 있나요?
gitudy 프로젝트 관련 readme.md 수정
더 추가할 예정입니다~
=> [ALL] refactor(#278): readme.md 파일 수정

README.md
#278
어떤 변경 사항이 있나요?
readme.md 수정
=> [ALL] refactor(#278): readme 수정

backend/src/main/java/com/example/backend/domain/define/fcm/listener/TodoUpdateMemberListener.java, backend/src/main/java/com/example/backend/domain/define/study/todo/event/TodoUpdateMemberEvent.java, backend/src/main/java/com/example/backend/study/api/controller/todo/StudyTodoController.java, backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java, backend/src/test/java/com/example/backend/domain/define/fcm/listener/TodoUpdateMemberListenerTest.java, backend/src/test/java/com/example/backend/domain/define/study/todo/TodoEventFixture.java, backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
ex) #274 
어떤 변경 사항이 있나요?
Todo를 수정 했을 때 알림 구현
특이사항 없습니다~!
=> [BE] feat(#274): Todo를 수정 했을 때 알림 구현

backend/src/main/java/com/example/backend/domain/define/study/commit/StudyCommit.java, backend/src/main/java/com/example/backend/domain/define/study/commit/constant/CommitStatus.java, backend/src/main/java/com/example/backend/study/api/controller/commit/StudyCommitController.java, backend/src/main/java/com/example/backend/study/api/controller/commit/request/CommitRejectionRequest.java, backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java, backend/src/test/java/com/example/backend/domain/define/study/commit/StudyCommitFixture.java, backend/src/test/java/com/example/backend/study/api/controller/commit/StudyCommitControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/commit/StudyCommitServiceTest.java
#288 
어떤 변경 사항이 있나요?
커밋 승인 및 거절 api 구현
=> [BE] feat(#288): 커밋 승인 및 거절 api 구현

backend/src/main/java/com/example/backend/auth/config/ProjectConfig.java
ex) #290 
어떤 변경 사항이 있나요?
LocalDateTime이 배열로 나오는 문제 -> LocalDateTime 포맷터 설정
=> [BE] fix: LocalDateTime 포맷터 설정

backend/src/main/java/com/example/backend/auth/config/ProjectConfig.java
=> [BE] refactor(#290): LocalDateTime사용

backend/build.gradle, backend/src/main/java/com/example/backend/domain/config/MongoConfig.java, backend/src/main/java/com/example/backend/domain/define/notice/Notice.java, backend/src/main/java/com/example/backend/domain/define/notice/repository/NoticeRepository.java, backend/src/test/java/com/example/backend/domain/define/notice/repository/NoticeRepositoryTest.java
ex) #285 
어떤 변경 사항이 있나요?
알림 목록 조회 api를 위한 mongo db 연동
Field : userId, title, message, time
로컬만 연결되어있고 아마 PR올리면 터질 거 같긴한데,
아직은 도커파일 변경하는 방법을 몰라서 서버에서는 오류날 것 같습니다..
=> [BE] feat(#285): mongo db연동

backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryCustom.java, backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java, backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoCountResponse.java, backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java, backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
ex) #300 
어떤 변경 사항이 있나요?
1. 마이 스터디 개수 조회 api 구현
2. 전체 스터디 개수 조회 api 구현
피드백 부탁드립니다~!
=> [BE] feat(#300) 스터디 개수 조회 api 구현

backend/src/main/java/com/example/backend/domain/define/study/info/StudyInfo.java, backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java, backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java, backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
#295 
어떤 변경 사항이 있나요?
스터디에 스터디원이 가입완료/강퇴/탈퇴시 해당스터디의 현재인원 증/감
빠진 부분있는지 피드백 부탁드립니다~
=> [BE] feat(#295): 스터디 현재인원 증/감 로직 추가

backend/src/main/java/com/example/backend/domain/define/notice/repository/NoticeRepository.java, backend/src/main/java/com/example/backend/domain/define/notice/repository/NoticeRepositoryCustom.java, backend/src/main/java/com/example/backend/domain/define/notice/repository/NoticeRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/event/controller/NoticeController.java, backend/src/main/java/com/example/backend/study/api/event/controller/response/UserNoticeList.java, backend/src/main/java/com/example/backend/study/api/event/service/NoticeService.java, backend/src/test/java/com/example/backend/domain/define/notice/NoticeFixture.java, backend/src/test/java/com/example/backend/study/api/event/controller/NoticeControllerTest.java, backend/src/test/java/com/example/backend/study/api/event/service/NoticeServiceTest.java
#304 
어떤 변경 사항이 있나요?
사용자의 알림 목록 조회 api
queryDSL로 작성하고싶었는데 mysql이랑 충돌도 나고 q-type도 못쓰고 적용이 쉽지가 않네요 ㅜㅜ
=> [BE] feat(#304): 알림 목록 조회 api

backend/src/main/java/com/example/backend/domain/define/fcm/listener/NotifyLeaderListener.java, backend/src/main/java/com/example/backend/domain/define/study/member/event/NotifyLeaderEvent.java, backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java, backend/src/main/java/com/example/backend/study/api/event/service/NoticeService.java, backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java, backend/src/test/java/com/example/backend/domain/define/fcm/listener/NotifyLeaderListenerTest.java, backend/src/test/java/com/example/backend/domain/define/study/member/MemberEventFixture.java, backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
#307 
어떤 변경 사항이 있나요?
팀원이 커밋시 팀장에게 알림갈수 있도록 api 구현
(프론트에서 버튼누를시 사용)
놓친부분 피드백 부탁드립니다!
=> [BE] feat(#307): 팀원이 팀장에게 알림 api

backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepository.java, backend/src/main/java/com/example/backend/study/api/controller/commit/StudyCommitController.java, backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java, backend/src/test/java/com/example/backend/domain/define/study/commit/StudyCommitFixture.java, backend/src/test/java/com/example/backend/study/api/controller/commit/StudyCommitControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/commit/StudyCommitServiceTest.java
#303 
스터디장의 승인/거절을 기다리는 커밋 리스트 조회 api 구현
놓친 부분 있으면 피드백 주세요!
=> feat(#303): 스터디장의 승인/거절을 기다리는 커밋 리스트 조회 api 구현

backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java, backend/src/main/java/com/example/backend/common/exception/notice/NoticeException.java, backend/src/main/java/com/example/backend/domain/define/notice/repository/NoticeRepository.java, backend/src/main/java/com/example/backend/study/api/event/controller/NoticeController.java, backend/src/main/java/com/example/backend/study/api/event/service/NoticeService.java, backend/src/test/java/com/example/backend/domain/define/notice/repository/NoticeRepositoryTest.java, backend/src/test/java/com/example/backend/study/api/event/controller/NoticeControllerTest.java, backend/src/test/java/com/example/backend/study/api/event/service/NoticeServiceTest.java
#309 
어떤 변경 사항이 있나요?
특정알림 삭제와 전체 알림 삭제 api
피드백 부탁드립니다!
=> [BE] feat(#309): 알림 삭제 api

backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepository.java, backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepository.java, backend/src/main/java/com/example/backend/study/api/scheduler/config/AsyncConfig.java, backend/src/main/java/com/example/backend/study/api/scheduler/config/SchedulingConfig.java, backend/src/main/java/com/example/backend/study/api/scheduler/service/ScheduledCommitFetchService.java, backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java, backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java, backend/src/test/java/com/example/backend/MockTestConfig.java, backend/src/test/java/com/example/backend/TestConfig.java, backend/src/test/java/com/example/backend/study/api/scheduler/service/ScheduledCommitFetchServiceTest.java, backend/src/test/java/com/example/backend/study/api/service/commit/CommitFetchPerformanceTest.java, backend/src/test/java/com/example/backend/study/api/service/commit/CommitFetchServiceTest.java, backend/src/test/java/com/example/backend/study/api/service/commit/StudyCommitServiceTest.java, backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
#312 
- 커밋 패치 로직 분리
- 커밋 패치 로직 스케줄링 적용
맞는지 잘 모르겠네요ㅠ;
기존 커밋 패치 테스트들이 스케줄링 때문에 제대로 테스트할 수 없어서 스케줄링 관련 테스트는 주석처리하고 애플리케이션 실행 후 30분 뒤부터 스케줄링되도록 설정해두겠습니다~
=> feat(#312): 커밋 패치 로직 스케줄링 적용

backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepository.java, backend/src/main/java/com/example/backend/study/api/controller/todo/StudyTodoController.java, backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java, backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java, backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
#319 
1. 스케줄링 범위 조정
- 기존: -3일 ~ 오늘 
- 수정: -3일 이후 전부
2. 기존의 Todo 전체 리스트 조회시 Commit Fetch를 무조건 하도록 되어 있었는데 fetchFlag 파라미터를 추가해서 true, false로 커밋 패치 여부를 선택하도록 수정했습니다.
3. 새로고침 버튼용 Todo 전체 리스트 Commit Fetch 로직을 구현했습니다.
=> [BE] feat(#319): 커밋 패치 로직 최적화

backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoDetailResponse.java, backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
ex) #이슈번호
어떤 변경 사항이 있나요?
레포지토리 정보 리턴
=> [BE] fix(#322): 스터디 상세정보 수정

backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java, backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoDetailResponse.java, backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoListResponse.java, backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java, backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
ex) #이슈번호
어떤 변경 사항이 있나요?
스터디 상세정보 조회 api, 스터디 목록 조회 api 필드에 리더인지 확인하는 isLeader 필드 추가
=> [BE] fix(#322): isLeader 필드 추가

android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/MyStudyRVAdapter.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyMainActivity.kt, android/gitudy/presentation/src/main/res/layout/activity_my_study_main.xml
#329
어떤 변경 사항이 있나요?
마이스터디 메인 페이지 내에서 To-Do 정보를 나타내는 기능 구현
- /study/{studyInfoId}/todo api 호출
=> [AN] feat(#329): 마이스터디 메인 페이지 내 to do 정보 api 호출 기능 구현

backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepository.java, backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryCustom.java, backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/controller/commit/StudyCommitController.java, backend/src/main/java/com/example/backend/study/api/controller/todo/StudyTodoController.java, backend/src/main/java/com/example/backend/study/api/controller/todo/response/StudyTodoListAndCursorIdxResponse.java, backend/src/main/java/com/example/backend/study/api/controller/todo/response/StudyTodoWithCommitsResponse.java, backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java, backend/src/test/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryTest.java, backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
#332 
어떤 변경 사항이 있나요?
- todo 전체 조회 시 커밋 리스트를 포함해 반환하도록 수정했습니다.
- todo id별 커밋 리스트 조회 api를 구현했습니다.
=> [BE] feat(#332): todo 전체 조회 시 커밋 리스트를 포함해 반환

android/gitudy/data/src/main/java/com/takseha/data/dto/feed/StudyListResponse.kt, android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/Commit.kt, android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/TodoListResponse.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/FeedRVAdapter.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/MyStudyRVAdapter.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/FeedHomeFragment.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/StudyApplyActivity.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/home/MainHomeFragment.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/CommitConventionActivity.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyHomeFragment.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyMainActivity.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/MakeStudyViewModel.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/StudyApplyViewModel.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/home/MainHomeViewModel.kt, android/gitudy/presentation/src/main/res/layout/activity_study_apply.xml, android/gitudy/presentation/src/main/res/layout/fragment_feed_home.xml, android/gitudy/presentation/src/main/res/layout/fragment_main_home.xml, android/gitudy/presentation/src/main/res/layout/fragment_my_study_home.xml
#337
어떤 변경 사항이 있나요?
스터디 가입 신청 페이지의 정보를 구성하는 로직을 구현한다.
https://github.com/DKU-Dgaja/gitudy/assets/86196342/377b3c79-6d99-4993-a03d-c73cf8514d05
스터디 배경색 변경 로직 적용했는데, 새로 생성되는 스터디부터 적용됩니당 -> 기존 스터디 배경은 검정색으로 표시됨
=> [AN] feat(#337): 스터디 신청 페이지전체 스터디 상세 페이지 로직 구현

backend/src/main/java/com/example/backend/domain/define/study/commit/constant/CommitStatus.java, backend/src/main/java/com/example/backend/domain/define/study/info/constant/StudyStatus.java, backend/src/main/java/com/example/backend/domain/define/study/member/StudyMember.java, backend/src/main/java/com/example/backend/domain/define/study/member/constant/StudyMemberStatus.java, backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
#341 
- enum 타입 필드 text 길이 조절
- Study member status 디폴트 값 waiting으로 변경
=> [BE] refactor(#341): enum 타입 data truncated 에러

backend/src/main/java/com/example/backend/domain/define/study/member/StudyMember.java, backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
=> [BE] refactor(#341): 스터디 가입 로직 수정

android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/member/GitudyMemberApi.kt, android/gitudy/data/src/main/java/com/takseha/data/dto/feed/MessageRequest.kt, android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/RogerResponse.kt, android/gitudy/data/src/main/java/com/takseha/data/repository/member/GitudyMemberRepository.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/firebase/MyFirebaseMessagingService.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/auth/SocialLoginCompleteActivity.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/common/CustomDialog.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/StudyApplyActivity.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/AddTodoActivity.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyMainActivity.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/StudyApplyViewModel.kt, android/gitudy/presentation/src/main/res/layout/activity_study_apply.xml, android/gitudy/presentation/src/main/res/layout/fragment_study_apply.xml, android/gitudy/presentation/src/main/res/layout/layout_dialog.xml, android/gitudy/presentation/src/main/res/values/strings.xml
#340
어떤 변경 사항이 있나요?
스터디 신청 페이지에서 스터디 신청 api와 스터디 신청 알림 전송 api를 호출하는 기능 구현
- /member/{studyInfoId}/apply api 호출
https://github.com/DKU-Dgaja/gitudy/assets/86196342/b7fe6429-202e-4216-89fa-de50fbc1c2e2
=> An feat(#340) 스터디 신청 페이지 스터디 신청 및 알림 api 호출 기능 구현

backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java, backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java, backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
#341 
스터디 멤버 수 증가 로직 임시로 추가
- 스터디 가입 신청 시 바로 증가되도록
=> [BE] fix(#341): 스터디 멤버 수 증가 로직 추가

backend/src/main/java/com/example/backend/study/api/controller/todo/response/StudyTodoResponse.java, backend/src/main/java/com/example/backend/study/api/controller/todo/response/StudyTodoWithCommitsResponse.java, backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
=> [BE] refactor(#341): Todo 응답 DTO 수정

backend/src/main/java/com/example/backend/auth/config/ProjectConfig.java
=> [Be] refactor(#354): cors 설정 수정

backend/src/main/java/com/example/backend/domain/define/study/comment/study/repository/StudyCommentRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/controller/comment/study/response/StudyCommentResponse.java
ex) #이슈번호
어떤 변경 사항이 있나요?
StudyComment 조회 DTO content필드 추가
=> [BE] refactor(#356): DTO 수정

backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepository.java, backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepositoryCustom.java, backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java, backend/src/main/java/com/example/backend/study/api/service/github/GithubApiService.java, backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java, backend/src/test/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepositoryTest.java, backend/src/test/java/com/example/backend/study/api/service/commit/CommitFetchPerformanceTest.java, backend/src/test/java/com/example/backend/study/api/service/commit/CommitFetchServiceTest.java, backend/src/test/java/com/example/backend/study/api/service/commit/StudyCommitServiceTest.java, backend/src/test/java/com/example/backend/study/api/service/convention/StudyConventionServiceTest.java, backend/src/test/java/com/example/backend/study/api/service/github/GithubApiServiceTest.java, backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
#361 
커밋 패치 로직 전반적인 수정
기존 비동기적으로 작동하던 커밋 패치 로직을 일단은 비활성화했습니다.
비동기가 아니라서 좀 걸리겠지만 일단 잘 불러오는지 확인부터 하고 적용해야 할 것 같아요
=> [Be] fix(#361): 커밋 패치 로직이 작동하지 않는 문제 발생

backend/src/main/java/com/example/backend/study/api/scheduler/service/ScheduledCommitFetchService.java
#363 
스케줄링 임시 비활성화
커밋 패치 로직 먼저 고치고 다시 구현하겠습니다 ㅠㅠ
=> [BE] refactor(#363): 스케줄링 임시 비활성화

backend/src/main/java/com/example/backend/study/api/controller/info/request/StudyInfoRegisterRequest.java
ex) #이슈번호
어떤 변경 사항이 있나요?
import문 추가 
=> [BE] fix(#369) 충돌해결 #369

android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/FeedRVAdapter.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/SplashActivity.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/SplashViewModel.kt
#359
어떤 변경 사항이 있나요?
앱 실행 시 기존 token이 유효한지 확인하여 token이 유효하면 로그인을 생략한다.
화이팅!!
=> [AN] feat(#359): 앱 실행 시 token 유효하면 로그인 생략하는 기능 구현

backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoListAndCursorIdxResponse.java, backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoListWithMemberResponse.java, backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java, backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java, backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
ex) #이슈번호
어떤 변경 사항이 있나요?
UserInfo를 포함하는 StudyMemberWithUserInfoResponse DTO생성
놓친 점 말씀해주세요~!
=> [BE] refactor(#372): 스터디 리스트 조회 dto 리팩토링

backend/src/main/java/com/example/backend/study/api/controller/commit/StudyCommitController.java, backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java, backend/src/test/java/com/example/backend/auth/api/service/jwt/JwtServiceTest.java
=> [BE] feat(#378): 커밋 패치 로직 수정

backend/src/main/java/com/example/backend/domain/define/study/commit/StudyCommit.java, backend/src/main/java/com/example/backend/domain/define/study/commit/constant/CommitStatus.java, backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java, backend/src/test/java/com/example/backend/domain/define/study/commit/StudyCommitFixture.java, backend/src/test/java/com/example/backend/study/api/service/commit/CommitFetchPerformanceTest.java, backend/src/test/java/com/example/backend/study/api/service/commit/CommitFetchServiceTest.java, backend/src/test/java/com/example/backend/study/api/service/commit/StudyCommitServiceTest.java
=> [BE] refactor(#378): 커밋 상태 필드 길이 조정

backend/src/main/java/com/example/backend/domain/define/study/commit/StudyCommit.java, backend/src/main/java/com/example/backend/domain/define/study/commit/constant/CommitStatus.java, backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java, backend/src/test/java/com/example/backend/domain/define/study/commit/StudyCommitFixture.java, backend/src/test/java/com/example/backend/study/api/service/commit/CommitFetchPerformanceTest.java, backend/src/test/java/com/example/backend/study/api/service/commit/CommitFetchServiceTest.java, backend/src/test/java/com/example/backend/study/api/service/commit/StudyCommitServiceTest.java
=> [BE] refactor(#378): 커밋 상태 필드 복구

backend/src/main/java/com/example/backend/domain/define/study/commit/StudyCommit.java, backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java, backend/src/test/java/com/example/backend/study/api/service/commit/CommitFetchServiceTest.java, backend/src/test/java/com/example/backend/study/api/service/commit/StudyCommitServiceTest.java
#378 
커밋 대기중 상태 인식 못하는 문제로 승인으로 임시 변경한 후 테스트해보고 다시 돌려두겠습니다~
=> [BE] refactor(#378): 커밋 대기중 상태 인식 못하는 문제로 승인으로 임시 변경

README.md
어떤 변경 사항이 있나요?
readme 파일 수정
readme에 영상 추가했어용
=> [ALL] Chore: README.md 수정

backend/src/main/java/com/example/backend/domain/define/study/info/constant/StudyStatus.java, backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoListResponse.java, backend/src/main/java/com/example/backend/study/api/controller/info/response/StudyInfoListWithMemberResponse.java, backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java, backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
ex) #385
어떤 변경 사항이 있나요?
1. STUDY_INACTIVE(스터디 비활성화) 필드 추가
2. 스터디 조회 response DTO에 status 추가
3. STUDY_DELETED는 조회할 수 없도록 쿼리 수정
4. 변경된 테스트 수정 및 추가
리뷰 부탁드립니다~!
=> [BE] refactor(#385)   비활성화 스터디 추가

.github/workflows/CICD_dev_be_merge.yml, .github/workflows/CI_dev_be_pull_request.yml
ex) #이슈번호
어떤 변경 사항이 있나요?
backend 하위 폴더가 변경되었을때에만 CI/CD 액션이 동작하도록 변경
=> [CI/CD] 깃헙액션

backend/src/main/java/com/example/backend/auth/config/security/filter/JwtAuthenticationFilter.java, backend/src/main/java/com/example/backend/common/exception/GlobalExceptionHandler.java, backend/src/main/java/com/example/backend/common/response/JsonResult.java, backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java, backend/src/test/java/com/example/backend/common/exception/GlobalExceptionHandlerTest.java
#398 
어떤 변경 사항이 있나요?
Jwt 토큰 예외관련 반환코드를 (기존 400 (BAD_REQUEST) -> 현재 401 (UNAUTHORIZED) 로 변경)
=> [BE] refactor(#398): Jwt 예외 반환코드 수정

.github/workflows/CICD_dev_be_merge.yml, webhooks/Dockerfile
=> feat: Dockerfile 추가

.github/workflows/CICD_dev_be_merge.yml
=> chore: GithubActions 수정

.github/workflows/CICD_dev_be_merge.yml
=> chore: path rule 추가

.github/workflows/CICD_dev_be_merge.yml
=> chore: 배포 시 도커 이미지 제거 추가

webhooks/src/main/kotlin/site/gitudy/webhooks/config/MongoDBConfig.kt
=> feat: mongodb _class 필드 제거설정

backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java, backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java, backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java, backend/src/test/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/category/info/CategoryControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/comment/commit/CommitCommentControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/comment/study/StudyCommentControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/commit/StudyCommitControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/convention/StudyConventionControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java, backend/src/test/java/com/example/backend/study/api/event/controller/FcmControllerTest.java, backend/src/test/java/com/example/backend/study/api/event/controller/NoticeControllerTest.java
#408 
어떤 변경 사항이 있나요?
reissue 는 프론트에서 refreshtoken으로 보내주니까 별로 고칠게 없네용
logout이랑 reissue 모두 TOKEN_INDEX 으로 처리하도록 했습니다!
놓친거있으면 피드백 해주세여~~
=> [BE] refactor(#408): reissue 수정

backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java, backend/src/main/java/com/example/backend/auth/api/service/jwt/JwtService.java, backend/src/main/java/com/example/backend/auth/api/service/state/LoginStateService.java, backend/src/main/java/com/example/backend/auth/api/service/token/RefreshTokenService.java, backend/src/main/java/com/example/backend/study/api/service/category/info/CategoryService.java, backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java, backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
#422 
어떤 변경 사항이 있나요?
1. createJwtToken , generateJwtToken 중복메서드 단일화
2. 회원탈퇴로직 수정
3.  Optional 객체 .orElseThrow() 변경 -> (Supplier는 예외 객체를 생성하는 람다식을 throw가 아닌 반환(return) 해야 한다.
Throwable supplier doesn't return any exception 오류 발생할 수 있음)
4. 안쓰는 메서드 삭제
=> [BE] refactor(#422): 중복메서드 리팩토링

backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java, backend/src/main/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkController.java, backend/src/main/java/com/example/backend/study/api/controller/category/info/CategoryController.java, backend/src/main/java/com/example/backend/study/api/controller/comment/commit/CommitCommentController.java, backend/src/main/java/com/example/backend/study/api/controller/commit/StudyCommitController.java, backend/src/main/java/com/example/backend/study/api/controller/convention/StudyConventionController.java, backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java, backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java, backend/src/main/java/com/example/backend/study/api/controller/todo/StudyTodoController.java
#425 
어떤 변경 사항이 있나요?
1. 스웨거 응답 수정 (멤버조회, 커밋조회)
2. 코드정렬
=> [BE] refactor(#425): 스웨거 응답 수정

backend/src/main/java/com/example/backend/study/api/controller/comment/commit/CommitCommentController.java, backend/src/main/java/com/example/backend/study/api/controller/member/StudyMemberController.java
=> [BE] fix: swagger error

backend/src/main/java/com/example/backend/auth/config/security/SecurityConfig.java
#429 
시큐리티 권한 설정을 수정했습니다
원래는 전부 허용했다가 하나씩 추가하려니까 잔실수들이 생기네요 🥲
=> [BE] refactor(#429): 시큐리티 설정 변경

backend/src/main/java/com/example/backend/auth/config/security/SecurityConfig.java, backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
=> [BE] refactor(#445): 시큐리티 권한 임시 허용

backend/src/main/java/com/example/backend/auth/config/security/SecurityConfig.java
=> [BE] refactor(#445): 시큐리티 설정 복구

webhooks/src/main/kotlin/site/gitudy/webhooks/common/error/GlobalExceptionHandler.kt, webhooks/src/main/kotlin/site/gitudy/webhooks/infrastructure/gitudy/WebhookClient.kt
=> feat: change webclient url

webhooks/src/main/kotlin/site/gitudy/webhooks/infrastructure/gitudy/WebhookClient.kt
=> refeat: baseUrl 변경

backend/src/main/java/com/example/backend/study/api/controller/todo/response/StudyTodoResponse.java, backend/src/main/java/com/example/backend/study/api/controller/todo/response/StudyTodoWithCommitsResponse.java
ex) #453
어떤 변경 사항이 있나요?
**프론트 요청 사항**
>commit 관련 DTO에 createdDateTime 필드를 추가한다.
<br>
1. @get("/study/{studyInfoId}/todo") DTO에 추가
```
변경 전                                                            변경 후
```
<br>
2. @get("/study/{studyInfoId}/todo/{todoId}") DTO에 추가
```
변경 전                                                            변경 후
```
없습니다~!
=> [BE] refactor(#453): 스터디 생성 날짜 추가

backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java, backend/src/main/java/com/example/backend/study/api/service/github/GithubApiService.java, backend/src/main/java/com/example/backend/study/api/service/github/GithubApiTokenService.java, backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java, backend/src/test/java/com/example/backend/auth/api/service/jwt/JwtServiceTest.java, backend/src/test/java/com/example/backend/domain/define/study/github/repository/GithubApiTokenRepositoryTest.java, backend/src/test/java/com/example/backend/domain/define/study/todo/mapping/repository/StudyTodoMappingRepositoryTest.java, backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/commit/StudyCommitServiceTest.java, backend/src/test/java/com/example/backend/study/api/service/github/GithubApiTokenServiceTest.java, backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java, backend/src/test/java/com/example/backend/webhook/api/service/WebhookServiceTest.java
#468 
- 충돌 해결 
- 사용하지 않는 의존성 제거
=> [BE] fix(#468): merge conflict

backend/src/main/java/com/example/backend/auth/config/security/SecurityConfig.java, backend/src/main/java/com/example/backend/study/api/controller/info/StudyInfoController.java, backend/src/main/java/com/example/backend/study/api/controller/info/request/StudyInfoRegisterRequest.java, backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/info/StudyInfoServiceTest.java
=> [BE] refactor(#474): 재발급 url 시큐리티 설정 수정

backend/src/main/java/com/example/backend/study/api/controller/todo/StudyTodoController.java, backend/src/main/java/com/example/backend/study/api/controller/todo/response/StudyTodoProgressResponse.java, backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java, backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java, backend/src/main/java/com/example/backend/webhook/api/service/WebhookService.java, backend/src/test/java/com/example/backend/domain/define/study/todo/StudyTodoFixture.java, backend/src/test/java/com/example/backend/domain/define/study/todo/mapping/repository/StudyTodoMappingRepositoryTest.java, backend/src/test/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryTest.java, backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java, backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
#482 
투두 진행률 조회 api 수정했습니다!
놓친 부분 있으면 피드백 주세요~
=> [BE] refactor(#482): 투두 진행률 조회 api 수정

backend/src/main/java/com/example/backend/domain/define/study/comment/commit/repository/CommitCommentRepositoryCustom.java, backend/src/main/java/com/example/backend/domain/define/study/comment/commit/repository/CommitCommentRepositoryImpl.java, backend/src/main/java/com/example/backend/domain/define/study/comment/study/repository/StudyCommentRepositoryCustom.java, backend/src/main/java/com/example/backend/domain/define/study/comment/study/repository/StudyCommentRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/controller/comment/commit/CommitCommentController.java, backend/src/main/java/com/example/backend/study/api/controller/comment/commit/response/CommitCommentInfoResponse.java, backend/src/main/java/com/example/backend/study/api/controller/comment/study/StudyCommentController.java, backend/src/main/java/com/example/backend/study/api/controller/comment/study/response/StudyCommentResponse.java, backend/src/main/java/com/example/backend/study/api/service/comment/commit/CommitCommentService.java, backend/src/main/java/com/example/backend/study/api/service/comment/study/StudyCommentService.java, backend/src/test/java/com/example/backend/auth/config/fixture/UserFixture.java, backend/src/test/java/com/example/backend/domain/define/study/comment/StudyCommentFixture.java, backend/src/test/java/com/example/backend/domain/define/study/comment/commit/repository/CommitCommentRepositoryTest.java, backend/src/test/java/com/example/backend/domain/define/study/comment/study/repository/StudyCommentRepositoryTest.java, backend/src/test/java/com/example/backend/study/api/controller/comment/commit/CommitCommentControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/comment/study/StudyCommentControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/comment/commit/CommitCommentServiceTest.java, backend/src/test/java/com/example/backend/study/api/service/comment/study/StudyCommentServiceTest.java
ex) #478
어떤 변경 사항이 있나요?
1. comment 형식 통일: 스터디 방명록과 커밋 댓글 둘 다 프로필 사진 클릭하면 댓글 작성자의 간단 프로필 볼 수 있도록 comment 형식을 통일한다.
2. /study/{studyInfoId}/comments: 댓글 생성일자(created_date_time) 반환을 추가 한다.
3. 내 댓글인지 아닌지 boolean으로 반환하는 isMyComment 필드를 추가한다.
---
1. isMyComment 필드 추가
2. created_date_time 필드 추가
3. 상세한 user_info 반환
```
변경 전                                                       변경 후
```
<br>
1. isMyComment 필드 추가
```
변경 전                                                       변경 후
```
[커밋_댓글_리스트_조회_실패_테스트]에서
getCommitCommentsList(any(Long.class)) -> getCommitCommentsList(any(Long.class), any(Long.class)) 변경 시 테스트 오류가 나는데  해결 못해서 일단 주석처리했습니다. 한번씩 봐주세요..ㅠㅠ
=> [BE] refactor(#478) : DTO 수정

backend/src/main/java/com/example/backend/study/api/controller/category/info/CategoryController.java, backend/src/main/java/com/example/backend/study/api/service/category/info/CategoryService.java, backend/src/main/java/com/example/backend/study/api/service/category/info/response/CategoryResponse.java, backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java, backend/src/main/java/com/example/backend/webhook/api/service/WebhookService.java, backend/src/test/java/com/example/backend/study/api/controller/category/info/CategoryControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/category/info/CategoryServiceTest.java, backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java, backend/src/test/java/com/example/backend/webhook/api/service/WebhookServiceTest.java
=> [BE] feat(#485): 카테고리 전체 조회 api 구현

backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/controller/member/response/StudyMembersResponse.java, backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
ex) #489 
어떤 변경 사항이 있나요?
/member/{studyInfoId} DTO 수정
```
변경 전                                      변경 후      
```
이상 없으면 머지해서 사용하시면 됩니다! @saesang
=> [BE] refactor(#489) 스터디 멤버 조회 반환 수정

backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java, backend/src/main/java/com/example/backend/auth/api/service/oauth/OAuthService.java, backend/src/main/java/com/example/backend/domain/define/study/comment/study/repository/StudyCommentRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/controller/comment/study/response/StudyCommentResponse.java, backend/src/test/java/com/example/backend/domain/define/study/comment/StudyCommentFixture.java, backend/src/test/java/com/example/backend/study/api/controller/comment/commit/CommitCommentControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/github/GithubApiServiceTest.java
=> [BE] fix(#496): 깃허브 토큰 저장 에러 수정

backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java, backend/src/main/java/com/example/backend/auth/api/service/rank/RankingService.java, backend/src/main/java/com/example/backend/auth/api/service/rank/event/StudyScoreSaveEvent.java, backend/src/main/java/com/example/backend/auth/api/service/rank/event/StudyScoreUpdateEvent.java, backend/src/main/java/com/example/backend/auth/api/service/rank/event/UserScoreSaveEvent.java, backend/src/main/java/com/example/backend/auth/api/service/rank/event/UserScoreUpdateEvent.java, backend/src/main/java/com/example/backend/domain/define/rank/listener/StudyScoreSaveListener.java, backend/src/main/java/com/example/backend/domain/define/rank/listener/StudyScoreUpdateListener.java, backend/src/main/java/com/example/backend/domain/define/rank/listener/UserScoreSaveListener.java, backend/src/main/java/com/example/backend/domain/define/rank/listener/UserScoreUpdateListener.java, backend/src/main/java/com/example/backend/domain/define/study/info/StudyInfo.java, backend/src/main/java/com/example/backend/domain/define/study/member/StudyMember.java, backend/src/main/java/com/example/backend/study/api/controller/comment/commit/request/AddCommitCommentRequest.java, backend/src/main/java/com/example/backend/study/api/service/comment/commit/CommitCommentService.java, backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java, backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java, backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java, backend/src/test/java/com/example/backend/study/api/service/comment/commit/CommitCommentServiceTest.java, backend/src/test/java/com/example/backend/study/api/service/commit/StudyCommitServiceTest.java
#493 
어떤 변경 사항이 있나요?
- 유저 점수
: 회원가입(10점) + 스터디 생성(5점) + 스터디 가입(5점) + 커밋 승인(2점) + 커밋 리뷰(1점)
- 스터디 멤버 활동점수(기여도)
: 커밋 승인(2점) + 커밋 리뷰(1점)
- 스터디 점수
: 멤버 활동점수 총합
- 스터디같은경우에는 기존 점수가 없어서 생성시에 기본 1점으로 초기화하도록 변경했습니다~
- 스터디 점수는 멤버별 점수의 총합이기에 멤버별로 따로 점수를 합하기 보단 커밋승인과 커밋 리뷰시에 동일하게 스터디점수가 추가되도록 구현했습니다.
놓친거있으면 피드백 부탁드립니다!
=> [BE] refactor(#493): 점수 로직 추가

backend/build.gradle, backend/src/main/java/com/example/backend/auth/config/security/SecurityConfig.java
#499 
- actuator 및 prometheus 의존성 추가
- actuator endpoint 시큐리티 설정
- application 환경 설정 수정
일단 의존성만 추가해두고 이것저것 테스트해봐야 할 것 같아요. 로컬에서는 잘 작동하는 거 확인했습니다!
=> [BE] feat(#499): actuator & prometheus 의존성 추가 및 시큐리티 설정

backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepositoryCustom.java, backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepositoryImpl.java, backend/src/main/java/com/example/backend/domain/define/study/todo/info/StudyTodo.java, backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
=> [BE] refactor(#502): 이제는 필요 없는 투두 코드 잔여물 삭제

backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/controller/member/response/StudyMemberApplyResponse.java
#511 
어떤 변경 사항이 있나요?
프론트 요청에 따라 프로필 열람 가능 여부 필드를 추가한다.
GET(/member/{studyInfoId}/apply)
: 여기에서 내 프로필 열람 가능 여부 필드 필요
=> [BE] refactor(#511): 프로필 공개여부 추가

backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
ex) #510
어떤 변경 사항이 있나요?
existsStudyMemberByUserIdAndStudyInfoId -> isWaitingStudyMemberByUserIdAndStudyInfoId 변경
=> [BE] fix(#510): 재사용 함수 수정

backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryImpl.java
ex) #510
어떤 변경 사항이 있나요?
문제 : 마이스터디 개수 조회할 때 study_waiting 상태인 스터디도 조회 되었다.
>STUDY_ACTIVE 상태인 마이스터디 개수만 조회하도록 수정
=> [BE] refactor(#510): 스터디 개수 조회 쿼리 수정

backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/controller/member/response/StudyMemberApplyListAndCursorIdxResponse.java, backend/src/main/java/com/example/backend/study/api/controller/member/response/StudyMemberApplyResponse.java, backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java
#516 
어떤 변경 사항이 있나요?
GET(/member/{studyInfoId}/apply)
studyTopic. created_date_time 필드 추가
=> [BE] refactor(#516): 스터디 가입 목록 조회 필드 수정

android/gitudy/data/src/main/java/com/takseha/data/api/gitudy/GitudyAuthService.kt, android/gitudy/data/src/main/java/com/takseha/data/dto/auth/auth/UserInfoUpdatePageResponse.kt, android/gitudy/data/src/main/java/com/takseha/data/dto/auth/auth/UserInfoUpdateRequest.kt, android/gitudy/data/src/main/java/com/takseha/data/dto/auth/register/CheckNicknameRequest.kt, android/gitudy/data/src/main/java/com/takseha/data/dto/mystudy/SocialInfo.kt, android/gitudy/data/src/main/java/com/takseha/data/repository/gitudy/GitudyAuthRepository.kt, android/gitudy/presentation/src/main/AndroidManifest.xml, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/auth/InputNicknameFragment.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyMainActivity.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/profile/ProfileEditActivity.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/profile/ProfileHomeFragment.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/RegisterViewModel.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/AddTodoViewModel.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/profile/ProfileEditViewModel.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/profile/ProfileHomeViewModel.kt, android/gitudy/presentation/src/main/res/drawable/box_non_stroke_r85.xml, android/gitudy/presentation/src/main/res/drawable/box_non_stroke_r85_black.xml, android/gitudy/presentation/src/main/res/drawable/box_stroke_200_r85.xml, android/gitudy/presentation/src/main/res/drawable/selector_btn_r85_enable.xml, android/gitudy/presentation/src/main/res/drawable/selector_btn_stroke_r12_focused.xml, android/gitudy/presentation/src/main/res/drawable/selector_switch.xml, android/gitudy/presentation/src/main/res/drawable/selector_text_color_enable_white.xml, android/gitudy/presentation/src/main/res/drawable/switch_track_off.xml, android/gitudy/presentation/src/main/res/layout/activity_commit_convention.xml, android/gitudy/presentation/src/main/res/layout/activity_profile_edit.xml, android/gitudy/presentation/src/main/res/layout/fragment_make_study1.xml, android/gitudy/presentation/src/main/res/layout/fragment_study_apply_message.xml, android/gitudy/presentation/src/main/res/layout/fragment_update_todo.xml, android/gitudy/presentation/src/main/res/values/strings.xml
#528 
어떤 변경 사항이 있나요?
회원정보 수정 및 조회 기능을 구현하였다.
일단 동영상은 안 올리겠습니다!! 바빠용
=> [AN] feat(#528): 회원정보 수정 및 조회 기능 구현

backend/src/main/java/com/example/backend/domain/define/fcm/listener/CommitRegisterListener.java, backend/src/main/java/com/example/backend/domain/define/fcm/listener/StudyApplyApproveRefuseListener.java, backend/src/main/java/com/example/backend/domain/define/fcm/listener/StudyApplyListener.java, backend/src/main/java/com/example/backend/domain/define/fcm/listener/TodoRegisterListener.java, backend/src/main/java/com/example/backend/domain/define/fcm/listener/TodoUpdateListener.java, backend/src/main/java/com/example/backend/domain/define/study/commit/event/CommitRegisterEvent.java, backend/src/main/java/com/example/backend/study/api/event/service/NoticeService.java, backend/src/main/java/com/example/backend/webhook/api/service/WebhookService.java
#523 
어떤 변경 사항이 있나요?
알림 메시지 형식 재수정 + 커밋 등록 알림 추가
=> [BE] refactor(#523): 알림 메시지 형식 재수정 + 커밋 등록 알림 추가

backend/src/main/java/com/example/backend/common/exception/ExceptionMessage.java, backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java, backend/src/test/java/com/example/backend/study/api/service/member/StudyMemberServiceTest.java
#524 
어떤 변경 사항이 있나요?
GET(/member/{studyInfoId}/apply/{applyUserId})
: 현재 스터디 가입 신청 목록이 없을 때 400이 반환됨 → 200 반환 및 빈 배열 반환하도록 변경 필요
=> [BE] refactor(#524): 스터디 가입신청 목록 반환 수정

backend/src/main/java/com/example/backend/domain/define/fcm/listener/StudyApplyApproveRefuseListener.java, backend/src/main/java/com/example/backend/study/api/event/service/NoticeService.java
=> [BE] refactor(#533): 알림 이모지 테스트

backend/src/main/java/com/example/backend/auth/config/security/filter/JwtAuthenticationFilter.java, backend/src/main/java/com/example/backend/study/api/service/github/GithubApiService.java, backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
#535 
- 깃허브 토큰을 찾을 수 없는 에러 발생
- 로그 간소화
의심되는 코드 몇 줄 지워봤어요. 이후에도 안 되면 바로 말해주세요!
=> [BE] fix(#535): 깃허브 토큰을 찾을 수 없는 에러 발생

backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java, backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepository.java, backend/src/main/java/com/example/backend/domain/define/study/info/repository/StudyInfoRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkController.java, backend/src/main/java/com/example/backend/study/api/service/github/GithubApiService.java, backend/src/main/java/com/example/backend/study/api/service/github/GithubApiTokenService.java, backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java, backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java, backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java, backend/src/main/java/com/example/backend/webhook/api/controller/request/WebhookPayload.java, backend/src/main/java/com/example/backend/webhook/api/service/WebhookService.java, backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/bookmark/StudyBookmarkControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/category/info/CategoryControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/comment/commit/CommitCommentControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/comment/study/StudyCommentControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/commit/StudyCommitControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/convention/StudyConventionControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/info/StudyInfoControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/member/StudyMemberControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java, backend/src/test/java/com/example/backend/study/api/event/controller/FcmControllerTest.java, backend/src/test/java/com/example/backend/study/api/event/controller/NoticeControllerTest.java, backend/src/test/java/com/example/backend/webhook/api/controller/WebhookControllerTest.java
#549 
- 에러 원인을 찾기 위한 로그 심기
- 사용하지 않는 의존성 제거
- 테스트 성능 향상을 위해 andDo(print()) 전부 제거
깃허브 토큰을 찾을 수 없다는 에러가 다시 발생하면 말해주세요~
=> [BE] fix(#549): 깃허브 토큰을 못 찾는 에러의 원인을 찾기 위한 로그 심기

backend/src/main/java/com/example/backend/auth/api/controller/auth/AuthController.java, backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java, backend/src/main/java/com/example/backend/domain/define/account/user/User.java, backend/src/main/java/com/example/backend/study/api/controller/member/request/MessageRequest.java, backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java, backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java, backend/src/test/java/com/example/backend/auth/api/service/rank/RankingServiceTest.java, backend/src/test/java/com/example/backend/domain/define/fcm/repository/FcmTokenRepositoryTest.java
#544 
어떤 변경 사항이 있나요?
유저 탈퇴시 이유 필드 추가
=> [BE] refactor(#544): 유저 탈퇴 이유 필드 추가

webhooks/src/main/kotlin/site/gitudy/webhooks/domain/webhook/WebhookService.kt, webhooks/src/main/kotlin/site/gitudy/webhooks/infrastructure/gitudy/dto/WebhookCommitRequest.kt
ex) #이슈번호
어떤 변경 사항이 있나요?
webhook 서버 요청 payload를 변경했습니다.
=> refact: webhook payload

backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java
=> [BE] refactor(#539): fcmToken 저장오류

backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepositoryImpl.java, backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java, backend/src/main/java/com/example/backend/study/api/service/commit/response/CommitInfoResponse.java, backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java, backend/src/main/java/com/example/backend/study/api/service/user/UserService.java, backend/src/test/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryTest.java, backend/src/test/java/com/example/backend/study/api/service/commit/StudyCommitServiceTest.java
#562 
어떤 변경 사항이 있나요?
커밋 리스트 사용자 이름 필드 추가
=> [BE] refactor(#562): 커밋 리스트 필드 추가

backend/src/main/java/com/example/backend/domain/define/study/commit/repository/StudyCommitRepositoryImpl.java, backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java, backend/src/main/java/com/example/backend/study/api/service/commit/response/CommitInfoResponse.java, backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java, backend/src/main/java/com/example/backend/study/api/service/user/UserService.java
#566 
어떤 변경 사항이 있나요?
커밋 리스트 사용자 프로필 url 필드 추가
=> [BE] refactor(#566): 커밋 리스트 필드 추가

backend/src/main/java/com/example/backend/auth/config/ProjectConfig.java
ex) #이슈번호
#568 
어떤 변경 사항이 있나요?
서울시간으로 초기화
=> [BE] refactor(#568): LocalDateTime mapper 수정

backend/src/main/java/com/example/backend/auth/api/service/rank/RankingService.java, backend/src/main/java/com/example/backend/auth/api/service/rank/response/StudyRankingResponse.java, backend/src/main/java/com/example/backend/auth/api/service/rank/response/UserRankingResponse.java, backend/src/test/java/com/example/backend/auth/api/service/rank/RankingServiceTest.java
=> [BE] refactor(#572): 스코어 호출 오류

backend/src/main/java/com/example/backend/study/api/service/info/StudyInfoService.java
#572 
어떤 변경 사항이 있나요?
스터디 초기점수 수정
=> [BE] refactor(#572): 스터디 초기점수 수정

backend/src/main/java/com/example/backend/domain/define/study/info/StudyInfo.java, backend/src/main/java/com/example/backend/webhook/api/service/WebhookService.java, backend/src/test/java/com/example/backend/domain/define/study/info/StudyInfoFixture.java, backend/src/test/java/com/example/backend/webhook/api/service/WebhookServiceTest.java
#575 
커밋 시 last commit date 업데이트 로직 구현
피드백 주세요~
=> [BE]: feat(#575): 커밋 시 last commit date 업데이트 로직 구현

backend/src/main/java/com/example/backend/domain/define/study/comment/commit/repository/CommitCommentRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/controller/comment/commit/CommitCommentController.java, backend/src/main/java/com/example/backend/study/api/controller/comment/commit/response/CommitCommentInfoResponse.java
#579
어떤 변경 사항이 있나요?
커밋 댓글 리스트 반환 DTO의 수정일 필드를 삭제했습니다.
9월도 파이텡~
=> [BE] refactor(#579): 커밋 댓글 리스트 반환 DTO 수정

backend/src/main/java/com/example/backend/study/api/controller/comment/commit/CommitCommentController.java, backend/src/test/java/com/example/backend/study/api/controller/comment/commit/CommitCommentControllerTest.java
=> [BE] refactor(#579): 커밋 댓글 등록 API 수정

backend/src/main/java/com/example/backend/domain/define/fcm/listener/CommitRegisterListener.java, backend/src/main/java/com/example/backend/domain/define/fcm/listener/ResignMemberListener.java, backend/src/main/java/com/example/backend/domain/define/fcm/listener/WithdrawalMemberListener.java, backend/src/main/java/com/example/backend/study/api/event/service/NoticeService.java, backend/src/main/java/com/example/backend/study/api/service/commit/StudyCommitService.java, backend/src/main/java/com/example/backend/webhook/api/service/WebhookService.java
#583 
어떤 변경 사항이 있나요?
커밋 메시지 알림 오류 해결 build(); 를 빼먹어서 알림이 안갔네요 ㅎㅎ..
=> [BE] refactor(#583): 커밋 메시지 알림 오류 + 문구 수정

backend/src/main/java/com/example/backend/study/api/controller/comment/commit/CommitCommentController.java, backend/src/test/java/com/example/backend/study/api/controller/comment/commit/CommitCommentControllerTest.java
=> [BE] refactor(#579): 커밋 댓글 수정, 삭제 API 수정

backend/src/main/java/com/example/backend/study/api/controller/commit/StudyCommitController.java, backend/src/main/java/com/example/backend/study/api/controller/todo/StudyTodoController.java, backend/src/main/java/com/example/backend/study/api/controller/todo/response/StudyTodoProgressResponse.java, backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java, backend/src/test/java/com/example/backend/domain/define/study/todo/StudyTodoFixture.java, backend/src/test/java/com/example/backend/study/api/controller/commit/StudyCommitControllerTest.java, backend/src/test/java/com/example/backend/study/api/controller/todo/StudyTodoControllerTest.java, backend/src/test/java/com/example/backend/study/api/service/todo/StudyTodoServiceTest.java
#588 
- 투두 프로그래스에 투두 매핑 완료 여부 추가
- 커밋 거절 로직 수정
=> [BE] refactor(#588): UI 피드백 반영 및 사소한 버그 수정

backend/src/main/java/com/example/backend/auth/api/controller/auth/request/AuthRegisterRequest.java, backend/src/main/java/com/example/backend/auth/api/service/auth/AuthService.java, backend/src/main/java/com/example/backend/auth/api/service/auth/request/AuthServiceRegisterRequest.java, backend/src/main/java/com/example/backend/domain/define/account/user/User.java, backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java, backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
#596 
- 로그인 시 토큰을 통해 githubId 받도록 수정
- 회원가입 시 githubId 입력받지 않도록 수정
피드백 주세요~
=> [BE] refactor(#596): 회원가입 시 github Id 입력받지 않도록 수정

backend/src/main/java/com/example/backend/domain/define/account/user/User.java, backend/src/test/java/com/example/backend/auth/api/service/auth/AuthServiceTest.java
#605 
어떤 변경 사항이 있나요?
회원탈퇴 로직 수정
=> [BE] refactor(#605): 회원 탈퇴 로직 수정

backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/service/todo/StudyTodoService.java
=> [BE] refactor(#611): 서버 시간 불일치 문제 해결

backend/src/main/java/com/example/backend/domain/define/study/member/repository/StudyMemberRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java, backend/src/test/java/com/example/backend/domain/define/fcm/repository/FcmTokenRepositoryTest.java
#604 
어떤 변경 사항이 있나요?
스터디 재가입 방지 수정 ACTIVE상태 에러 반환 메세지 수정
=> [BE] refactor(#604): 스터디 재가입 방지 수정

android/gitudy/data/src/main/java/com/takseha/data/token/TokenManager.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/SplashActivity.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/home/MainHomeActivity.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/profile/PersonalInfoTermFragment.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/LoginViewModel.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/LoginWebViewViewModel.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/RegisterViewModel.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/auth/SplashViewModel.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/common/BaseApplicationViewModel.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/common/BaseViewModel.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/MakeStudyViewModel.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/feed/StudyApplyViewModel.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/AddTodoViewModel.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/CommitDetailViewModel.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/mystudy/StudyApplyMemberProfileViewModel.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/profile/ProfileEditViewModel.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/viewmodel/profile/SettingHomeViewModel.kt, android/gitudy/presentation/src/main/res/layout/fragment_personal_info_term.xml, android/gitudy/presentation/src/main/res/navigation/setting_nav.xml
#619
어떤 변경 사항이 있나요?
네트워크 에러 생길 시 스낵바 안 뜨는 에러를 해결하였다!!
- 각 ViewModel의 함수에서 onError()를 재정의하면 BaseViewModel의 onError()가 적용되지 않아 발생하는 문제였음
: 각 ViewModel의 onError()에서 BaseViewModel의 onError()를 super로 상속받게 해서 해결함
- TokenManager의 함수가 호출되는 경우 error처리가 제대로 되지 않는 상황 발생
: throw e로 간단하게 해결되었음..
이제 진짜 배포만 남았다...!!!!
=> [AN] fix(#619): 네트워크 에러 생길 시 스낵바 안 뜨는 에러 해결

.github/workflows/CI_dev_be_pull_request.yml, backend/src/main/java/com/example/backend/auth/api/controller/auth/request/UserNameRequest.java, backend/src/test/java/com/example/backend/auth/api/controller/auth/AuthControllerTest.java
#621 
닉네임 글자 제한은 프론트에서만 하도록 수정했습니다!
=> [BE] refactor(#621): 닉네임 글자 제한 수정

backend/src/main/java/com/example/backend/auth/api/controller/auth/request/UserNameRequest.java, backend/src/main/java/com/example/backend/domain/define/study/info/StudyInfo.java, backend/src/main/java/com/example/backend/domain/define/study/todo/repository/StudyTodoRepositoryImpl.java, backend/src/main/java/com/example/backend/study/api/service/member/StudyMemberService.java, backend/src/test/java/com/example/backend/study/api/service/info/StudyManagementServiceTest.java
#634 
studyinfo info 필드 속성 text로 변경
=> [BE] refactor: studyinfo info 필드 속성 text로 변경

android/gitudy/app/build.gradle.kts, android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/CommitCommentListRVAdapter.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/DetailCommentListRVAdapter.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/adapter/ToDoListRVAdapter.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/FeedHomeFragment.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyHomeFragment.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/StudyCommentBoardFragment.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/ToDoFragment.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/profile/CommitDetailFragment.kt, android/gitudy/presentation/src/main/res/layout/fragment_main_home.xml, android/gitudy/presentation/src/main/res/layout/item_comment_detail.xml, android/gitudy/presentation/src/main/res/layout/item_commit_comment.xml, android/gitudy/presentation/src/main/res/menu/report_menu.xml, android/gitudy/presentation/src/main/res/values/strings.xml
#638 
어떤 변경 사항이 있나요?
배포 전 최종 버전 기능 및 UI 확정
🥹🚀🔥✨🥹🚀🔥✨🥹🚀🔥✨🥹🚀🔥✨
첫 시도만에 프로덕션 액세스 통과했습니다!!!!!!!
🥹🚀🔥✨🥹🚀🔥✨🥹🚀🔥✨🥹🚀🔥✨
다들 진짜 고생 많았다!!!!!!!!!!!!!!ㅠㅠㅠㅠㅠㅠㅠ
앞으로도 업데이트 꾸준히 고고 ^_^
=> [AN] refactor(#638): 배포 전 최종 수정 - 프로덕션 액세스 통과 :)

android/gitudy/app/build.gradle.kts, android/gitudy/data/src/main/java/com/takseha/data/sharedPreferences/SP.kt
#645
어떤 변경 사항이 있나요?
AEADBadTagException 및 KeyStoreException 에러로 인해 발생하는 앱의 비정상종료를 해결하였다.
: EncryptedSharedPreferences의 키 인증과 관련된 문제로, SP 관련 에러 발생 시 SP를 초기화한 후 사용자가 다시 로그인하게 하는 방식으로 해결한다.
비정상종료 버그 수정했습니다^_^
=> [AN] fix(#645): AEADBadTagException 및 KeyStoreException 에러 처리

android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/FeedHomeFragment.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/feed/StudyApplyInfoFragment.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/home/MainHomeAlertFragment.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/home/MainHomeFragment.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyHomeFragment.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/MyStudyMainFragment.kt, android/gitudy/presentation/src/main/java/com/takseha/presentation/ui/mystudy/ToDoFragment.kt
#648 
어떤 변경 사항이 있나요?
스터디 목록 데이터, 스터디 메인 화면 등에서 데이터 중복 로딩 코드 리팩토링
: onCreate, onResume 중복 코드 삭제
- MainHomeFragment 수정
- FeedHomeFragment 수정
- MyStudyHomeFragment 수정
- MyStudyMainFragment 수정
- ToDoFragment 수정
- StudyApplyInfoFragment 수정
- MainHomeAlertFragment 수정
=> [AN] refactor(#648): 데이터 로딩 관련 성능 개선
